src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp
=> [mscAlgorithmPaint] 'save' button name

src-plugins/iterativeClosestPoint/iterativeClosestPointProcess.cpp, src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src-plugins/iterativeClosestPoint/vtkICPFilter.cxx, src-plugins/iterativeClosestPoint/vtkICPFilter.h
Following this issue: https://github.com/Inria-Asclepios/medInria-public/issues/1
* Change QCheckBox to QComboBox and add a description
* Remove the tab which is useless
* Change the title to "Iterative Closest Point", clearer name for user
:m:
=> [ICP] ergonomy button and tab

app/medInria/main.cpp
Small PR to change the qDebug message at MUSIC launch from a terminal.
:m:
=> [terminal] help log at MUSIC launch

src-plugins/medMaskApplication/medMaskApplicationToolBox.cpp, src-plugins/reformat/reformatToolBox.cpp, src/medCore/medMessageController.cpp
=> [messageController] add messages in maskAppli and reformat

CMakeLists.txt, src-plugins/itkDataImage/readers/itkGDCMDataImageReader.cpp, src-plugins/itkFilters/itkFiltersBinaryCloseProcess_p.h, src-plugins/itkFilters/itkFiltersBinaryOpenProcess_p.h, src-plugins/itkFilters/itkFiltersCloseProcess_p.h, src-plugins/itkFilters/itkFiltersOpenProcess_p.h, src-plugins/itkN4BiasCorrection/CMakeLists.txt, src-plugins/reformat/CMakeLists.txt, src/medImageIO/CMakeLists.txt, src/medRegistration/CMakeLists.txt, src/medVtkInria/CMakeLists.txt, src/medVtkInria/vtkDataManagement/vtkMetaDataSet.h
I don't know why github cannot merge it automatically, I'll do it manually.
This PR is then just to inform you that, unless veto from someone, I'll make the switch to ITK4.9 and cmake3 next week, probably on Monday.
This switch concerns every repo we are working on: the super project, this one, and the 2 plugins repo.
So if anyone is opposed to this switch, this is the time and the place to express it.
=> Itk4.9cmake3

src-plugins/manualRegistration/CMakeLists.txt, src-plugins/manualRegistration/manualRegistration.cpp, src-plugins/manualRegistration/manualRegistration.h, src-plugins/manualRegistration/manualRegistrationLandmarkController.cpp, src-plugins/manualRegistration/manualRegistrationLandmarkController.h, src-plugins/manualRegistration/manualRegistrationToolBox.cpp, src-plugins/manualRegistration/manualRegistrationToolBox.h
Changes a bit the way the tbx is done: the process is created inside the tbx and not inside the controller, adds a button to save the transformation in a txt or tfm (quite used in ITK) file.
=> Manual registration, saving transformation in a file

src-plugins/reformat/medResliceViewer.cpp, src-plugins/reformat/medResliceViewer.h, src-plugins/reformat/reformatPlugin.cpp, src-plugins/reformat/reformatWorkspace.h, src-plugins/reformat/resliceToolBox.cpp, src-plugins/reformat/resliceToolBox.h
medReformatViewer->medResliceViewer
reformatToolBox->resliceToolBox
Workspace named "Reformat"
Toolbox named "Reslice"
:m:
=> [ReformatTbx] named reslice, and reformat workspace

src-plugins/medClut/medClutToolBox.cpp
The `mapper2d` variable was never used.
:m:
=> [medClutTlbx] rm useless variable

src/medCore/database/medDatabaseReader.cpp
Solves https://github.com/Inria-Asclepios/medInria-public/issues/49.
=> [medDatabaseReader] add->set metadata

src/medUtilities/medUtilities.cpp
Needed in pipelines! The process name has been changed.
:m:
=> [medDecimateMeshProcess] change process name in medUtilities

src-plugins/medBinaryOperation/medBinaryOperatorBase.cpp
Nothing else to add, pretty simple and logical.
=> [BinaryOp] sets the right image type

src/medImageIO/itkDataImageWriterBase.cpp
Quick fix for https://github.com/Inria-Asclepios/medInria-public/issues/83
=> [itkDataImageWriterBase] only encapsulate proper metadata

CMakeLists.txt
Quick change to put back the versioning of the software.
=> [Versioning] 1.1.0

src-plugins/manualRegistration/manualRegistrationToolBox.cpp
From https://github.com/Inria-Asclepios/medInria-public/issues/100
Everything in title.
:m:
=> [manualRegistration] add explanation about landmarks

src-plugins/reformat/medCropToolBox.cpp
From https://github.com/Inria-Asclepios/medInria-public/issues/91
Add an error message in crop to help users to know what happened.
:m:
=> [medCropToolbox] error message when use wrong data

src-plugins/iterativeClosestPoint/iterativeClosestPointProcess.cpp, src-plugins/iterativeClosestPoint/iterativeClosestPointProcess.h, src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.h
From https://github.com/Inria-Asclepios/medInria-public/issues/90
Add showError to be clearer for the user. 
Add a progress bar.
:m:
=> [ICP] add showError, progressBar

src/medCore/database/medDatabaseModel.h, src/medCore/gui/commonWidgets/medSlider.h, src/medCore/gui/medSelectorWorkspace.h
Since I have the great luck to be back on Windows :'(, here are some changes for compatibility.
=> Windows compatibility

src/medCore/database/medDatabaseModel.h, src/medCore/gui/commonWidgets/medSlider.h, src/medCore/gui/medSelectorWorkspace.h
Same as what we just merged today on the _master_, except the merge is now on _integration_
So no particular need to review, just write a big yes ;)
=> Windob compatibility

src/medCore/gui/toolboxes/medSelectorToolBox.cpp
From https://github.com/Inria-Asclepios/medInria-public/issues/107
Change the name from "choose algorithm" to "choose a toolbox" (as in tooltip).
:m:
=> medSelectorToolbox name of combobox

src-plugins/itkFilters/itkFiltersToolBox.cpp
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/109
Set minimum at 1
:m:
=> [divideFilter] minimum value at 1

src-plugins/itkFilters/itkMorphologicalFiltersProcessBase_p.h
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/98
Standardize the way outputs are named.
:m:
=> [morphoFilters] standardize output filename

src-plugins/itkFilters/CMakeLists.txt, src-plugins/itkFilters/itkFiltersComponentSizeThresholdProcess_p.h, src-plugins/itkFilters/itkFiltersThresholdingProcess_p.h, src-plugins/itkFilters/itkFiltersWindowingProcess_p.h
From https://github.com/Inria-Asclepios/medInria-public/issues/126
Update Threshold, Component Threshold and Windowing
:m:
=> [basicFilters] output name standardisation

src-plugins/itkFilters/CMakeLists.txt, src-plugins/itkFilters/itkFiltersToolBox.cpp
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/89
Allow to use this toolbox with CT scan (negative values).
_--This PR uses this other one: https://github.com/Inria-Asclepios/medInria-public/pull/97 I will rebase it when the the other one is merged.--_ REBASED
:m:
=> [Windowing] set max and min for spinbox

app/medInria/medFilteringWorkspace.cpp, app/medInria/medRegistrationWorkspace.cpp, app/medInria/medRegistrationWorkspace.h, app/medInria/medSegmentationWorkspace.h, src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemons.cpp, src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsToolBox.cpp, src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsToolBox.h, src-plugins/manualRegistration/manualRegistrationToolBox.cpp, src-plugins/manualRegistration/manualRegistrationToolBox.h, src-plugins/undoRedoRegistration/undoRedoRegistrationToolBox.cpp, src/medCore/gui/medSelectorWorkspace.cpp, src/medCore/gui/medSelectorWorkspace.h, src/medCore/gui/toolboxes/medAbstractSelectableToolBox.cpp, src/medCore/gui/toolboxes/medRegistrationSelectorToolBox.cpp, src/medCore/gui/toolboxes/medRegistrationSelectorToolBox.h, src/medCore/gui/toolboxes/medSelectorToolBox.cpp, src/medCore/gui/toolboxes/medSelectorToolBox.h
`medRegistrationWorkspace` inherits from `medSelectorWorkspace`.
`medRegistrationSelectorToolBox` inherits from `medSelectorToolBox`.
The registration toolboxes (manual registration and diffeo**) inherit from `medSelectableToolBox`.
=> Adapts registration toolboxes to new system

CMakeLists.txt
Makes it compile on Windows after logFiles merge.
=> boost windows compatibility

app/medInria/medWorkspaceArea.cpp, src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src-plugins/manualRegistration/manualRegistrationToolBox.cpp, src-plugins/medClut/medClutToolBox.cpp, src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp, src-plugins/reformat/medCropToolBox.cpp, src-plugins/reformat/medResliceViewer.h, src-plugins/reformat/resliceToolBox.cpp
Following the "[medTabbedViewContainer] add function to get first container and view" https://github.com/Inria-Asclepios/medInria-public/pull/136 PR.
This PR adapts toolboxes to these new functions.
:m:
=> [medTabbedView] simplify updateView code (2)

src-plugins/reformat/medCropToolBox.cpp
Solves https://github.com/Inria-Asclepios/music/issues/367
(The PR that introduced this could not have worked properly. Please make sure changes are properly tested before making PRs, and also after making changes requested by reviewers)
=> [medCropToolBox] fixed user-splittable crash

app/medInria/medApplication.cpp, app/medInria/medHomepageArea.cpp, app/medInria/medHomepageArea.h
Crashes still happen when closing the app after using some vtk, itk processes : https://github.com/medInria/medInria-private/issues/104 for instance.
It comes from, itk/vtk forwarded messages that are being written in the dtkLogView while the app is closing.
Since we plan to deliver a dmg some time, I just propose to comment this for now.
=> comments the log redirection code

src-plugins/itkFilters/itkFiltersInvertProcess_p.h
=> [InvertIntensityFilter] Fixes intensity filter.

src/medUtilities/medUtilities.cpp, src/medUtilities/medUtilities.h
Convenient methods from music repo that could be used inside the core.
=> [medUtilities] bring minimum() and volume() from medPip*Utilities

src/medVtkInria/vtkImageView/vtkImageViewCornerAnnotation.cxx
Slice number and location on corner annotation now properly updated when interacting with the view.
FIxes #199 and all the other annotation problems when the slice changes.
Changes in code start from line 163 to line 176... the rest is indentation issues.
=> [vtkImageViewAnnotation] Update slice number and location on corner annotation

src-plugins/iterativeClosestPoint/iterativeClosestPointProcess.cpp, src-plugins/itkN4BiasCorrection/itkN4BiasCorrection.cpp, src-plugins/itkN4BiasCorrection/itkN4BiasCorrection_p.h, src-plugins/medBinaryOperation/itkNotOperator.cpp, src-plugins/medBinaryOperation/medBinaryOperatorBase.cpp
Based on https://github.com/Inria-Asclepios/medInria-public/issues/198
Create output inside the "Run" function, and not in `setInput()`.
Done in:
NotOperator
N4BiasCorrection
IterativeClosestPoint
medBinaryOperatorBase
:m:
=> [Not-N4-ICP-Bin] create output in run fct, not in setInput

CMakeLists.txt
=> versionning 1.1.2

src-plugins/itkFilters/itkFiltersComponentSizeThresholdProcess_p.h
From this issue https://github.com/Inria-Asclepios/medInria-public/issues/79
The output and input types of `itk::ConnectedComponentImageFilter` are not the same anymore. In that case, `unsigned char` dataset with a lot of components won't fail.
:m:
=> [componentSize] allow to have more than 256 objects in unsignedChar data

src/medCore/gui/commonWidgets/medSlider.cpp, src/medCore/gui/commonWidgets/medSlider.h
add tick count needed for pr #126
=> [medSlider] add tick count

app/medInria/main.cpp
From the discussion on this PR https://github.com/Inria-Asclepios/music/pull/458
It solves the bug using a script **path** with accents.
:m:
=> [Pip] switch to utf-8 before creation of medApplication

src/medCore/database/medDataManager.cpp, src/medCore/database/medDataManager.h
Small PR needed for this one https://github.com/Inria-Asclepios/music/pull/471
:m:
=> [cartoPip] allow to get signal at end of import

src/medCore/database/medAbstractDatabaseImporter.cpp
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/210
This Pull Request allows to stop the import of a file if the file is empty.
:m:
=> [Import] crash if empty file

src/medCore/data/medAbstractData.cpp, src/medCore/data/medAbstractImageData.cpp, src/medCore/data/medAbstractTypedImageData.h, src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medDataManager.cpp, src/medCore/medMessageController.cpp, src/medCore/views/medAbstractLayeredView.cpp, src/medVtkInria/vtkDataManagement/vtkDataManager.cxx, src/medVtkInria/vtkImageView/vtkImageView.cxx
Hop,
From this idea in this issue: https://github.com/Inria-Asclepios/medInria-public/issues/145
I made these changes for myself, to read more easily our logs. It can be interesting for everyone. I think that these outputs are not relevant for us.
:m:
=> [logs] remove useless logs, easier reading

src/medCore/database/medDatabaseModel.cpp, src/medCore/gui/database/medDatabaseCompactWidget.cpp, src/medCore/gui/database/medDatabaseCompactWidget.h, src/medCore/gui/database/medDatabasePreview.cpp, src/medCore/gui/database/medDatabaseSearchPanel.cpp, src/medCore/gui/database/medDatabaseSearchPanel.h
According to this issue: https://github.com/Inria-Asclepios/medInria-public/issues/152
Improve the search bar tool which was not really clear (euphemism), and was not known by manips.
=> [search bar] better ergonomy

src-plugins/itkFilters/itkFiltersToolBox.cpp
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/191
Explain what does exactly this Normalization filter.
:m:
=> [Normalization] add an explanation label

src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/146
Allows to explain what do the ICP parameters.
:m:
=> [ICP] add tooltips for obscure parameters

src/medCore/parameters/medDoubleParameter.cpp, src/medCore/parameters/medIntParameter.cpp
According to this issue https://github.com/Inria-Asclepios/medInria-public/issues/56 the manips wanted a larger handle in sliders. That's the goal of this Pull Request.
:m:
=> [sliders] larger slider handle in medIntParameter and medDoubleParameter

src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp, src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.h, src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medAbstractDatabaseImporter.h, src/medCore/database/medDatabaseController.cpp, src/medCore/database/medDatabaseReader.cpp, src/medImageIO/itkDCMTKImageIO.cpp, src/medImageIO/itkDataImageReaderBase.cpp
I worked on:
* this issue https://github.com/Inria-Asclepios/medInria-public/issues/154 about the warning logs that i have, and the pop-up that @LoicCadour has,
This problem is solved (cf `DCMTKImageIO::DCMTKImageIO()` ), and i clarified the way metadata are saved in `itkDCMTKDataImageReader::readInformation`.
:m:
=> [DB] remove itk warning & clean update of metadata

src/medCore/gui/database/medDatabaseView.cpp
From https://github.com/Inria-Asclepios/medInria-public/issues/237
Edit window does not show thumbnail path.
:m:
=> [DB] users not allowed to change ThumbnailPath

src-plugins/reformat/medCropToolBox.cpp
An addition of a small `include` forgotten in Crop.
:m:
=> [urgent] add an #include to compile crop

src-plugins/manualRegistration/manualRegistration.cpp, src-plugins/manualRegistration/manualRegistration.h, src-plugins/manualRegistration/manualRegistrationToolBox.cpp
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/223
This PR adds an Affine method to the Rigid one in Manual Registration.
:m:
=> [manualRegistration] add Affine method

src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medDatabaseImporter.cpp, src/medCore/database/medDatabaseModel.cpp, src/medCore/database/medDatabaseNonPersistentImporter.cpp, src/medCore/gui/database/medDatabaseSearchPanel.cpp
From this issue https://github.com/Inria-Asclepios/medInria-public/issues/248
"Serie" becomes "Series", and i removed a very small bug in the DB search combobox which displayed an empty line.
:m:
=> [DB] serie->series, and rm empty line in DB combobox

src-plugins/itkFilters/itkFiltersToolBox.cpp
From this issue https://github.com/Inria-Asclepios/medInria-public/issues/250
Explain that the minimum size is in pixel
:m:
=> [componentSizeThreshold] add that the size is in pixel

src/medCore/database/medDataManager.cpp, src/medCore/database/medDataManager.h, src/medCore/database/medDatabaseModel.cpp, src/medCore/gui/database/medDatabaseView.cpp, src/medCore/gui/medAbstractWorkspace.cpp, src/medCore/gui/viewContainers/medViewContainer.cpp, src/medCore/gui/viewContainers/medViewContainer.h
From this issue https://github.com/Inria-Asclepios/medInria-public/issues/255
Allow to drop a study in a view, or right-click->View on a study to open the series list in a view.
:m:
=> [DB] open a study with several series in a view

app/medInria/medFilteringWorkspace.cpp, src-plugins/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp, src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp, src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.h, src-plugins/itkDataImage/readers/itkGDCMDataImageReader.cpp, src-plugins/itkFilters/itkFiltersAddProcess_p.h, src-plugins/itkFilters/itkFiltersDivideProcess_p.h, src-plugins/itkFilters/itkFiltersGaussianProcess_p.h, src-plugins/itkFilters/itkFiltersInvertProcess_p.h, src-plugins/itkFilters/itkFiltersMedianProcess_p.h, src-plugins/itkFilters/itkFiltersMultiplyProcess_p.h, src-plugins/itkFilters/itkFiltersNormalizeProcess_p.h, src-plugins/itkFilters/itkFiltersShrinkProcess_p.h, src-plugins/itkFilters/itkFiltersSubtractProcess_p.h, src-plugins/medVtkFibersData/interactors/medVtkFibersDataInteractor.cpp, src-plugins/vtkDataMesh/interactors/vtkDataMesh4DInteractor.cpp, src-plugins/vtkDataMesh/readers/vtkDataMeshReader.cpp, src/medCore/data/medAbstractData.cpp, src/medCore/data/medAbstractData.h, src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medDatabaseController.cpp, src/medCore/database/medDatabaseNonPersistentImporter.cpp, src/medCore/gui/database/medDatabaseView.cpp, src/medCore/gui/toolboxes/medRegistrationSelectorToolBox.cpp, src/medImageIO/itkDataImageReaderBase.cpp, src/medRegistration/itkProcessRegistration.cpp, src/medUtilities/medUtilities.cpp
From the issue https://github.com/Inria-Asclepios/medInria-public/issues/262
As said on the issue, i've worked on the standardization of set/addmetadata since few PR, and it's a good idea to set it directly in medAbstractData.
:m:
=> [medAbstractData] add setMetaData function

CMakeLists.txt
=> [Version] medInria

src/medUtilities/medUtilities.cpp, src/medUtilities/medUtilities.h
From https://github.com/Inria-Asclepios/medInria-public/issues/295
Adds a maximumValue fonction in medUtilities for use in toolboxes or pipelines.
:m:
=> [medUtility] adds maximumValue fct

src-plugins/reformat/resliceToolBox.cpp
From this issue https://github.com/Inria-Asclepios/medInria-public/issues/125
One-line debug of a crash about start/stop with a change of parameter in Reslice.
:m:
=> [reslice] small crash after switch parameter

app/medInria/resources/authors.html, app/medInria/resources/medInria.qss, src-plugins/iterativeClosestPoint/iterativeClosestPointPlugin.cpp, src-plugins/iterativeClosestPoint/iterativeClosestPointPlugin.h, src-plugins/itkFilters/itkFiltersPlugin.cpp, src-plugins/itkFilters/itkFiltersToolBox.cpp, src-plugins/itkFilters/itkMorphologicalFiltersToolBox.cpp, src-plugins/itkN4BiasCorrection/itkN4BiasCorrectionPlugin.cpp, src-plugins/itkN4BiasCorrection/itkN4BiasCorrectionPlugin.h, src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsPlugin.cpp, src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsToolBox.cpp, src-plugins/manualRegistration/manualRegistrationPlugin.cpp, src-plugins/manualRegistration/manualRegistrationPlugin.h, src-plugins/medBinaryOperation/medBinaryOperationPlugin.cpp, src-plugins/medMaskApplication/medMaskApplicationPlugin.cpp, src-plugins/medMaskApplication/medMaskApplicationPlugin.h, src-plugins/mscAlgorithmPaint/mscAlgorithmPaintPlugin.cpp, src-plugins/reformat/reformatPlugin.cpp, src-plugins/reformat/reformatPlugin.h
Need to be rebased with https://github.com/Inria-Asclepios/medInria-public/pull/264 -- REBASED
From this issue https://github.com/Inria-Asclepios/music/issues/501, allows to fill the description area in the information/help button of a toolbox.
Commit: from https://github.com/Inria-Asclepios/medInria-public/pull/287/commits/6cdc695a7bac88cef4110e5369a536f74c1de00e
:m:
=> [Help] fill description with details/url

src/medCore/views/medAbstractLayeredView.cpp
Reverts Inria-Asclepios/medInria-public#270
=> Revert "[DataView] rm data: view was not re-initialized"

src-plugins/itkFilters/itkMorphologicalFiltersToolBox.cpp
Identical PR of https://github.com/Inria-Asclepios/medInria-public/pull/311 but on master branch. Already validated by @fcollot 
:m:
=> [Morpho] change max value of kernel

src/medCore/database/medDataManager.cpp, src/medCore/database/medDataManager.h
Needed for the upcoming PR that fixes the import of pipelines.
=> [medDataManager] getMetaData

src/medCore/gui/toolboxes/medSelectorToolBox.cpp
The signal was declared but never emitted.
=> [medSelectorToolBox] emit inputChanged signal

src/medCore/database/medDataManager.cpp
fixes https://github.com/Inria-Asclepios/medInria-public/issues/334
=> [medDataManager] fixed crash in get/setMetaData with invalid index

CMakeLists.txt
=> [Version] medInria 2.1.0

RELEASE_NOTES.txt
=> [RELEASE_NOTES] adds changes 2.1.0

app/medInria/medMainWindow.cpp, app/medInria/medWorkspaceArea.cpp, src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp, src-plugins/vtkDataMesh/navigators/vtkDataMeshNavigator.cpp, src-plugins/vtkDataMesh/navigators/vtkDataMeshNavigator.h
From this issue https://github.com/Inria-Asclepios/music/issues/586
Add possibility to change the view(s) background(s) for meshes and save it with the original screenshot tool. 
:m:
=> [Screenshot] can change view background and save it

src/medVtkInria/vtkDataManagement/vtkMetaDataSet.cxx, src/medVtkInria/vtkImageView/vtkImageView.cxx, src/medVtkInria/vtkImageView/vtkImageView3D.cxx
Remove small warnings seen in Jenkins compilation.
:m:
=> [warnings] rm warnings seen in Jenkins compil

src/medVtkInria/vtkDataManagement/vtkMetaDataSetSequence.cxx, src/medVtkInria/vtkDataManagement/vtkMetaImageData.cxx
Thanks to @LoicCadour this PR switches the ITK version from 4.9.0 to 4.11.1.
The 3 PR: 
* https://github.com/Inria-Asclepios/medinria-superproject/pull/18
* https://github.com/Inria-Asclepios/medInria-public/pull/350
* https://github.com/FBU-IHU-LIRYC/music-private/pull/130
Linked issue: https://github.com/Inria-Asclepios/medInria-public/issues/251
:m:
=> [ITK] switch to V4.11

src/medCore/database/medDataManager.cpp
From https://github.com/Inria-Asclepios/medInria-public/issues/345
If the extension of the filename is not the same as in the first one in the combobox, a search is done to convert to the format chosen by the user in the filename.
:m:
=> [Export] guess extension from filename if needed

src/medCore/views/medAbstractLayeredView.cpp
- Fix the "Attempt to add twice the same data" warning message.
=> [AbstractLayeredView] Fix add data twice

CMakeLists.txt
Number version for the next release.
:m:
=> [Release] version

src/medCore/database/medDataManager.cpp
From issue https://github.com/Inria-Asclepios/medInria-public/issues/380
Solve the obj error in automatic export of meshs.
:m:
=> [VTK] vtkDataMeshWriter top priority

src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medDatabaseImporter.cpp, src/medCore/database/medDatabaseNonPersistentImporter.cpp
From https://github.com/Inria-Asclepios/medInria-public/issues/366
Fill with default name the series description if empty.
:m:
=> [Import] if series name is empty, fill with default name

app/medInria/medWorkspaceArea.cpp, src-plugins/medVtkView/medVtkViewNavigator.cpp, src-plugins/medVtkView/medVtkViewNavigator.h, src-plugins/mscExportVideo/mscExportVideo.cpp, src/medCore/views/medAbstractImageView.cpp, src/medCore/views/medAbstractImageView.h, src/medCore/views/navigators/medAbstractImageViewNavigator.h
Tests pre-release: issue https://github.com/Inria-Asclepios/medInria-public/issues/387
Solves crashes with export of non-mesh video.
:m:
=> [Video] export do not crash with volume3D/4D

app/medInria/medWorkspaceArea.cpp, src-plugins/medVtkView/medVtkViewNavigator.cpp, src-plugins/medVtkView/medVtkViewNavigator.h, src-plugins/mscExportVideo/mscExportVideo.cpp, src/medCore/views/medAbstractImageView.cpp, src/medCore/views/medAbstractImageView.h, src/medCore/views/navigators/medAbstractImageViewNavigator.h
Tests pre-release: issue https://github.com/Inria-Asclepios/medInria-public/issues/388
Will be rebased with https://github.com/Inria-Asclepios/medInria-public/pull/389
PR needed for Release 2.2.0.
Thx to @mjuhoor \o
:m:
=> [Video] rotation export solves for non-centered meshes 

src-plugins/vtkDataMesh/writers/vtkDataMeshWriter.cpp
@mjuhoor this is working ^^'.
This is a debug PR for release 2.2.0. We were losing localization sometimes on linux.
Cf. issue https://github.com/Inria-Asclepios/medInria-public/issues/397
:m:
=> [Local] set good local for vtk writing

app/medInria/medWorkspaceArea.cpp
Issue https://github.com/Inria-Asclepios/medInria-public/issues/403
@fcollot do you still have the same problem with this code?
@mjuhoor long shot, but do you still have the first image with the window?
:m:
=> [Video] do not use grabWindow

src/medUtilities/medUtilities.cpp, src/medUtilities/medUtilities.h
- Add utility methods on vtk arrays:
- retrieve an array
- retrieve a value in an array
- compute array range
- compute array stats (mean and std deviation for now)
- The goal is to be able to use such functions in pipeline and code refactoring.
=> [medUtilities] Array utility methods

src-plugins/vtkDataMesh/readers/vtkDataMesh4DReader.cpp
- Fix empty 4D mesh when saved or exported.
Fixes #411
=> [vtkDataMesh4D] Critical bug fix

app/medInria/medHomepageArea.cpp
Change the url link on the Help button to the new online documentation.
:m:
=> [Doc] change link to music user manual

src-plugins/medVtkView/medVtkViewNavigator.cpp, src-plugins/medVtkView/medVtkViewNavigator.h, src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- Remove slicing parameter when in 3D view
- Add checkbox to enable/disable the annotated cube in 3D view
=> [medVtkViewNavigator] Slicing parameter and annotated cube

src/medUtilities/medUtilities.cpp, src/medUtilities/medUtilities.h, src/medVtkInria/vtkDataManagement/vtkMetaDataSet.h
- Add an utility method to retrieve array index and data type.
=> [medUtilities] Add utility methods

app/medInria/medWorkspaceArea.cpp
From the issue https://github.com/Inria-Asclepios/medInria-public/issues/423
Possibility to do screenshot of a single or multiple views.
:m:
=> [Screenshot] handle multiple views

src/medCore/data/medMetaDataKeys.cpp, src/medCore/data/medMetaDataKeys.h, src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medAbstractDatabaseImporter.h
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/359
The imagery team asked to know this kind of information in data from MUSIC. I used "Description" (instead of FilePaths) because it was not used at all, and this is easier to understand that some info/description are in "Description" than in "FilePaths".
:m:
=> [DB] generated by MUSIC x.y.z

src/medCore/gui/database/medDatabaseView.cpp
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/342
Add the possibility to edit a line from the database (idem in Browser) with the Edit Key: F2 on Linux for instance.
:m:
=> [DB] edit a line with Edit Key

src/medCore/database/medAbstractDatabaseImporter.cpp
Fix bug related to re-open data saved in MUSIC.
The entry IMAGE was not created anymore in DB.
=> [FIX] [DB] Create metaDataKey:FilePath 

src/medCore/database/medAbstractDatabaseImporter.cpp
-solves https://github.com/Inria-Asclepios/medInria-public/issues/455
=> [DataBaseImporter]: allow import and load from path with accents

src/medUtilities/medUtilitiesITK.h
fix https://github.com/Inria-Asclepios/music/issues/654
=> [medUtilitiesITK] avoid SWIG bug on variadic templates

src/medUtilities/medUtilitiesITK.cpp, src/medUtilities/medUtilitiesITK.h
(should) fix https://github.com/Inria-Asclepios/medInria-public/issues/466
=> [medUtilitiesITK] forward declaration of itkDataImageId

src-plugins/diffeomorphicDemons/diffeomorphicDemonsToolBox.h, src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.h, src-plugins/itkFilters/itkMorphologicalFiltersToolBox.h, src-plugins/itkN4BiasCorrection/itkN4BiasCorrectionToolBox.cpp, src-plugins/itkN4BiasCorrection/itkN4BiasCorrectionToolBox.h, src-plugins/manualRegistration/manualRegistrationToolBox.h, src-plugins/medBinaryOperation/medBinaryOperationToolBox.h, src-plugins/medClut/medClutToolBox.h, src-plugins/medMaskApplication/medMaskApplicationToolBox.h, src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.h, src-plugins/reformat/resliceToolBox.h, src-plugins/undoRedoRegistration/undoRedoRegistrationToolBox.h
With https://github.com/FBU-IHU-LIRYC/music-private/pull/184 , https://github.com/Inria-Asclepios/music/pull/643 and https://github.com/medInria/medInria-private/pull/172
Add toolbox documentation (and especially widget types used in pipelines) for the website https://music.gitlabpages.inria.fr/MUSICsoftware/
:m:
=> [Doxygen] add widget types names

app/medInria/medHomepageArea.cpp
From an issue on Mac https://github.com/Inria-Asclepios/music/issues/365
Tested on https://github.com/Inria-Asclepios/medInria-public/pull/421
The icon size has to be defined on Mac.
:m:
=> [Icon] size problem on Mac

app/medInria/medApplication.cpp, app/medInria/medHomepageArea.cpp, src/medCore/gui/settingsWidgets/medStartupSettingsWidget.cpp
As asked in https://github.com/Inria-Asclepios/medInria-public/issues/451
The dark theme is the default one.
:m:
=> [Theme] default dark theme

CMakeLists.txt
One line PR, increase number of version.
:m:
=> [Release] number++

src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp, src-plugins/reformat/medCropToolBox.cpp, src-plugins/reformat/medResliceViewer.cpp, src-plugins/reformat/medResliceViewer.h, src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medDatabaseController.cpp, src/medCore/database/medDatabaseController.h, src/medCore/database/medDatabaseImporter.cpp, src/medCore/database/medDatabaseReader.cpp, src/medCore/gui/database/mscDatabaseMetadataItemDialog.cpp, src/medCore/gui/database/mscDatabaseMetadataItemDialog.h, src/medUtilities/medUtilitiesITK.h
From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/434
Will be rebased with https://github.com/Inria-Asclepios/medInria-public/pull/432
Update metadata of a data after a reslice.
:m:
=>  [Reslice] update metadata after process 

README.md
Right link to the MUSIC documentation website.
:m:
=> [README] MUSIC website url

src/medImageIO/CMakeLists.txt, src/medRegistration/CMakeLists.txt, src/medVtkInria/CMakeLists.txt
Needed for https://github.com/Inria-Asclepios/medinria-superproject/pull/35 for @juliencastelneau 
As done in https://github.com/Inria-Asclepios/medInria-public/pull/461/files some libraries were not replaced by ${XXX_LIBRARIES} yet.
:m:
=> [CMakeLists] last XXX_LIBRARIES

app/medInria/resources/authors.html
Adds names to the list of authors.
:m:
=> [Authors] update with Julien and Nordine

RELEASE_NOTES.txt
To be merged after https://github.com/Inria-Asclepios/music/pull/620
Adds the channelness toolbox to release notes.
:m:
=> [ReleaseNotes] add Channelness toolbox

src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp
fixes https://github.com/Inria-Asclepios/medInria-public/issues/484
Importing Dicom, metadata with accents are convert to be displayed in the database.
:m:
=> [DB] patient name with accent wrongly displayed solved

src-plugins/vtkDataMesh/navigators/vtkDataMeshNavigator.cpp
- Makes depth peeling usable by massively decreasing render time.
=> [Depth peeling] Reduce number of maximum peels

src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- Fixes #477 , based on @nebatmusic master branch
=> [Slicing parameter] Fix orphan slicing parameter

src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp, src/medCore/gui/toolboxes/medToolBox.h, src/medCore/views/medAbstractLayeredView.h, src/medUtilities/medUtilitiesVTK.cpp
- Add templated method in medToolBox to retrieve a specific interactor from layered views.
=> [medToolBox] Add method to retrieve a specific layer interactor

src-plugins/itkFilters/itkFiltersBinaryThresholdingProcess.cpp, src-plugins/itkFilters/itkFiltersBinaryThresholdingProcess.h, src-plugins/itkFilters/itkFiltersPlugin.cpp, src-plugins/itkFilters/itkFiltersThresholdingProcess.cpp, src-plugins/itkFilters/itkFiltersToolBox.cpp, src-plugins/itkFilters/itkFiltersToolBox.h
1. Create new Process : BinaryThreshold
2. Modify Old ThresholdProcess with outside option 
a) greater than => The values greater than the threshold value are set to OutsideValue (as before)
b) lower than => The values less than the threshold value are set to OutsideValue (as before)
c) outside =>  The values outside the threshold range (less than lower or greater than upper) are set to OutsideValue
3. Modify Threshold toolbox to take in account the modifications above.
=> Threshold Modification

src-plugins/medVtkView/medVtkView.cpp
=> [FIX] Issue #513. 

src/medUtilities/medUtilities.cpp, src/medUtilities/medUtilities.h, src/medUtilities/medUtilitiesVTK.cpp
- Add utility method to compute mean and variance from samples in a QList
=> [medUtilities] Add function to compute mean and variance in medUtilities

src-plugins/itkFilters/itkFiltersToolBox.cpp, src/medUtilities/medUtilitiesITK.cpp, src/medUtilities/medUtilitiesITK.h
Utility methods mandatories for new AFCT Pipeline
=> Utility method used in Pipelines

src-plugins/itkFilters/CMakeLists.txt, src-plugins/itkFilters/itkFiltersToolBox.cpp, src-plugins/itkFilters/itkFiltersToolBox.h, src/medCore/data/medAbstractImageData.h, src/medCore/gui/lookUpTables/medClutEditor.cpp, src/medCore/gui/lookUpTables/medClutEditor.h, src/medCore/gui/toolboxes/medToolBox.cpp, src/medCore/gui/viewContainers/medViewContainer.cpp, src/medCore/gui/viewContainers/medViewContainer.h
Ability to show histogram when performing a threshold on image
The threshold values can be set from sliders or directly on histogram view
=> Histogram in threshold tool box

src-plugins/mscExportVideo/mscExportVideo.cpp, src-plugins/mscExportVideo/mscExportVideo.h
Fix https://github.com/Inria-Asclepios/medInria-public/issues/394
To be used with https://github.com/Inria-Asclepios/medinria-superproject/pull/43
Add FFMPEG and MPEG2 .avi exports.
MPEG2 is proprietary.
:m:
=> [AVI] FFMPEG and MPEG2

app/medInria/medFileSystemDataSource.cpp
Fixes https://github.com/Inria-Asclepios/medInria-public/issues/355
Path in File Systems is kept is you select a data.
:m:
=> [Browser] path saved in file system

src-plugins/reformat/medResliceViewer.cpp, src-plugins/reformat/medResliceViewer.h
Fixes https://github.com/Inria-Asclepios/medInria-public/issues/281
Remove an identifier warning starting Reslice.
:m:
=> [medResliceViewer] add identifier function to avoid warning

app/medInria/medMainWindow.cpp
From a @fcollot comment on https://github.com/Inria-Asclepios/medInria-public/pull/515
Solve the memory leak problem.
:m:
=> [Search] memory leak

src-plugins/mscExportVideo/mscExportVideo.cpp, src-plugins/mscExportVideo/mscExportVideo.h, src/medCore/gui/medAbstractWorkspace.cpp, src/medCore/gui/viewContainers/medViewContainer.cpp, src/medCore/gui/viewContainers/medViewContainer.h
Only this COMMIT: https://github.com/Inria-Asclepios/medInria-public/commit/4bb93bd733846245e0e2839e8542d819e0106ccd
This PR includes also the ffmpeg PR, but you can only look at the commit above.
Fixes https://github.com/Inria-Asclepios/medInria-public/issues/521
It really close the view (and the histogram) when the last layer of the view is removed from the Layer settings widget.
In fact i already fixed this problem in the VTK 7 PR https://github.com/Inria-Asclepios/medInria-public/pull/461/files, that's why it has been quick.
:m:
=> [View] close the view if last layer removed 

CMakeLists.txt, RELEASE_NOTES.txt
Switch to 2.4.0 version number.
Update Release Notes. Tell me if something is missing.
:m:
=> [2.4.0] Version + Release Notes

src-plugins/mscExportVideo/mscExportVideo.cpp
To be used with https://github.com/Inria-Asclepios/medinria-superproject/pull/59
MPEG2 on Linux binaries.
:m:
=> [Video] MPEG2 for linux and win for packaging error

src-plugins/mscExportVideo/mscExportVideo.cpp
Reverts Inria-Asclepios/medInria-public#540
=> Revert "[Video] MPEG2 for linux and win for packaging error"

src-plugins/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp, src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp, src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.h, src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp
Fixes https://github.com/Inria-Asclepios/medInria-public/issues/554
Add Ticks to slider with 4D volume for Paint Toolbox.
:m:
=> [Paint] add slider ticks to 4D volume

cmake/FindDCMTK.cmake, cmake/FixDCMTKMacInstall.cmake, cmake/FixDCMTKMacLink.cmake, src-plugins/itkDataImage/CMakeLists.txt
- Fix DCMTK packaging problem related to change to official DCMTK repo
=> [DCMTK] Fix link problem on macOS

CMakeLists.txt, cmake/FixDCMTKMacInstall.cmake, src-plugins/itkDataImage/CMakeLists.txt, src-plugins/qtdcmDataSource/CMakeLists.txt, src/medImageIO/CMakeLists.txt
Reverts Inria-Asclepios/medInria-public#561
=> Revert "[DCMTK/QtDCM] Fix macOS linking problem"

cmake/FindDCMTK.cmake, cmake/FixDCMTKMacInstall.cmake, cmake/FixDCMTKMacLink.cmake, src-plugins/itkDataImage/CMakeLists.txt
Reverts Inria-Asclepios/medInria-public#559
=> Revert "[DCMTK] Fix link problem on macOS"

cmake/FindDCMTK.cmake, cmake/FixDCMTKMacInstall.cmake, cmake/FixDCMTKMacLink.cmake, src-plugins/itkDataImage/CMakeLists.txt
Reverts Inria-Asclepios/medInria-public#565
A proper fix has been found
=> Revert "Revert "[DCMTK] Fix link problem on macOS"" !

CMakeLists.txt, cmake/FixDCMTKMacInstall.cmake, src-plugins/itkDataImage/CMakeLists.txt, src-plugins/qtdcmDataSource/CMakeLists.txt, src/medImageIO/CMakeLists.txt
Reverts Inria-Asclepios/medInria-public#564
A proper fix has been found
=> Revert "Revert "[DCMTK/QtDCM] Fix macOS linking problem""

src-plugins/iterativeClosestPoint/iterativeClosestPointProcess.cpp, src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src-plugins/iterativeClosestPoint/vtkICPFilter.cxx, src-plugins/iterativeClosestPoint/vtkICPFilter.h
=> [Iterative closest point] Adapt for EP maps

src/medVtkInria/medClutEditorToolBox/medClutEditorToolBox.cpp
From https://github.com/Inria-Asclepios/medInria-public/pull/539
Add delete of tables in destructor.
:m:
=> [ColorMap] remove pointer on tables²

superbuild/CMakeLists.txt, superbuild/projects_modules/music-plugins-liryc.cmake, superbuild/projects_modules/music-plugins.cmake
=> Renamed music plugin project and added liryc plugins

src-plugins/itkDataImage/itkDataImagePlugin.cpp, src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp, src-plugins/itkDataImage/readers/itkGDCMDataImageReader.cpp, src-plugins/itkDataImage/writers/itkDicomDataImageWriter.cpp, src-plugins/itkDataImage/writers/itkDicomDataImageWriter.h, src/medCore/data/medMetaDataKeys.cpp, src/medCore/data/medMetaDataKeys.h, src/medCore/database/medAbstractDatabaseImporter.cpp, src/medCore/database/medDatabaseController.cpp, src/medCore/database/medDatabaseImporter.cpp, src/medCore/database/medDatabaseNonPersistentController.cpp, src/medCore/database/medDatabaseNonPersistentImporter.cpp, src/medCore/database/medDatabaseNonPersistentItem.cpp, src/medCore/database/medDatabaseReader.cpp, src/medCore/gui/database/medDatabaseView.cpp, src/medImageIO/itkDCMTKImageIO.cpp, src/medImageIO/itkDCMTKImageIO.h, src/medImageIO/itkDataImageWriterBase.cpp, src/medUtilities/medUtilities.cpp
=> Add dicom writer

src/layers/legacy/medCoreLegacy/medViewEventFilter.cpp, src/layers/legacy/medCoreLegacy/medViewEventFilter.h
- Add mouse wheel events in the event filter. Those were available in music 2.
=> [medViewEventFilter] Mouse wheel events

src/layers/legacy/medCoreLegacy/medViewEventFilter.cpp, src/layers/legacy/medCoreLegacy/medViewEventFilter.h
- Correct implementation of mouse wheel events
=> [medViewEventFilter] Mouse wheel correction

superbuild/projects_modules/openssl.cmake
Solve linux package generation.
=> pb_linux_package1 :  Solve linux package generation 

superbuild/CMakeLists.txt, superbuild/projects_modules/music-plugins.cmake, superbuild/projects_modules/quazip.cmake
- Add QuaZip, a wrapper over zlib that enables simple archive compression and decompression.
- MUSIC can now read and create .zip archives
=> [QuaZip] Add QuaZip dependency

superbuild/projects_modules/quazip.cmake
- Download a tagged release
- Fixes #613
=> [QuaZip] Tagged release

superbuild/projects_modules/openssl.cmake
Without this changes I go errors du compilation or link step.
=> For openssl windows compil  

superbuild/projects_modules/openssl.cmake
=> Ssl for winb

superbuild/projects_modules/openssl.cmake
=> Ssl for winc

src/app/medInria/medMainWindow.cpp, src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medStartupSettingsWidget.cpp
Add https://github.com/medInria/medInria-public/pull/759 and solve a merge problem with icons that we declare above in a theme paragraph.
:m:
=> [MUSICardio3] merge problem with theme icons and generic workspace

src/layers/legacy/medUtilities/CMakeLists.txt, src/layers/legacy/medUtilities/medUtilities.cpp, src/layers/legacy/medUtilities/medUtilities.h
- Add function to generate DICOM UIDs
- Add function to add a StudyId and StudyInstanceUID to a medAbstractData
- Use gdcm to generate UIDs
=> [medUtilities] Generate UIDs using gdcm

src/layers/legacy/medUtilities/CMakeLists.txt
=> [medUtilities] Add ITK libraries in link step

superbuild/projects_modules/quazip.cmake
=> [quazip] Add Qt5_DIR for quazip

src/layers/legacy/medUtilities/medUtilities.cpp, src/layers/legacy/medUtilities/medUtilities.h, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/polygonRoi/polygonEventFilter.cpp
- Add function in medUtilities to retrieve the device pixel ratio
- Refactor code that uses device pixel ratio
N.B. as I don't have a retina screen, could someone else test if this works? It's only code refactoring but still...
=> [medUtilities] Retrieve device pixel ratio

src/plugins/legacy/meshManipulation/meshManipulationToolBox.cpp, src/plugins/legacy/meshManipulation/meshManipulationToolBox.h
Same as https://github.com/medInria/medInria-public/pull/767
=> [Mesh Manipulation] EP map fix

superbuild/patches/dtk-1.7.1.patch
=> [dtk] Change how dtk generates priorities

src/app/medInria/medMainWindow.cpp
This is an update of the minimum size of MUSICardio, particularly the height, since we added some workspaces.
:m:
=> [MUSICardio] our workspace: need to update min size of the app

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.cxx, src/layers/legacy/medVtkInria/vtkImageView/vtkImageView2D.h
- Send a signal with slice number and view orientation when a slice is changed
=> [vtkImageView] View 2D now sends a signal when the slice changes

src/app/medInria/resources/music_lightGrey.qss, src/layers/legacy/medCoreLegacy/gui/viewContainers/medViewContainer.cpp, src/plugins/legacy/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp, src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp
- fix color background selected items in QComboBox 
- remove empty spase around mesh interactor toolbar
=> [Theme]: fix color background 

superbuild/projects_modules/quazip.cmake
- Change tag
- Use BUILD_SHARED_LIBS=OFF
**Requires cmake >= 3.15**
=> [Quazip] Change to tag v1.1

src/app/medInria/CMakeLists.txt, src/app/medInria/medLogger.cpp
Get https://github.com/medInria/medInria-public/pull/787 in our fork.
:m:
=> [Boost&MedLoger] merge from medInria

superbuild/projects_modules/asio.cmake, superbuild/projects_modules/websocketpp.cmake
Since soon will be released MusicCardio, use stable branch of 2  dependencies
=> use stable release instead of master

superbuild/projects_modules/jsoncons.cmake
=> [jsoncons]Remove install command from jsoncons

packaging/apple/mac_packager.sh.in, src/layers/legacy/medCoreLegacy/data/medMetaDataKeys.h, src/layers/legacy/medCoreLegacy/views/navigators/medAbstractImageViewNavigator.cpp, src/layers/legacy/medUtilities/medUtilitiesITK.cpp, src/layers/legacy/medUtilities/medUtilitiesITK.h, src/layers/legacy/medUtilities/statsROI.cpp, src/layers/legacy/medUtilities/statsROI.h, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.cxx, src/plugins/legacy/LCCLogDemons/LCCLogDemonsPlugin.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemonsPlugin.h, src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.h, src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusPlugin.h, src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusToolBox.cpp, src/plugins/legacy/itkProcessRegistrationOptimus/itkProcessRegistrationOptimusToolBox.h, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/medRemeshing/medRefineMeshProcess.cpp
Update from medInria 3.2 to MUSICardio 3.0 for the beta release.
:m:
=> Merge beta3.0 musi cardio

src/cmake/module/set_plugin_install_rules.cmake
From https://github.com/medInria/medInria-public/pull/822
:m:
=> [Package] solve packaging pb on Ubuntu with .so files

superbuild/projects_modules/DCMTK.cmake, superbuild/projects_modules/ITK.cmake, superbuild/projects_modules/VTK.cmake
Merge from medInria to MUSICardio to compile and package every external projects with patchs.
From https://github.com/medInria/medInria-public/pull/823
:m:
=> Patch med inria

superbuild/projects_modules/music-plugins.cmake
Fix https://github.com/Inria-Asclepios/medInria-public/issues/660 
There was a warning during music-plugins compilation due to mmg.
:m:
=> [Warning] MMG_SRC_DIR not used

doxygen.conf
1-line PR: the MUSICardio logo name changed
:m:
=> [Doxygen] icon name changed: MUSICardio

src/layers/legacy/medCoreLegacy/database/medDataManager.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp
- Fix compilation errors due to incorrect merge conflict resolution
=> Fix merge errors

superbuild/projects_modules/eigen.cmake
Like what has been done for json. 
Will allow an easier build with find_package.
=> improve eigen cmake to have generated build files (config.cmake,...) 

superbuild/projects_modules/music-plugins.cmake
Forgot to put back the right music plugins branch in the Windows PR.
:m:
=> [music] put back right musicPlugins branch

superbuild/projects_modules/quazip.cmake, superbuild/projects_modules/zlib.cmake
- Fixes quazip and music-plugins compilation error
=> [zlib] Enable default install step for zlib

src/CMakeLists.txt, superbuild/CMakeLists.txt, superbuild/projects_modules/asio.cmake, superbuild/projects_modules/jsoncons.cmake, superbuild/projects_modules/medInria.cmake, superbuild/projects_modules/music-plugins.cmake, superbuild/projects_modules/openssl.cmake, superbuild/projects_modules/websocketpp.cmake
As done for ffmpeg, the realtime workspace is OFF by default.
If USE_RealTimeWorkspace is OFF then these libraries are OFF:
* jsoncons
* asio
* websocketpp
* openssl
:m:
=> [Realtime] off by default with libs

packaging/apple/settings.json
Link to https://github.com/Inria-Asclepios/medInria-public/pull/703
This PR updates the Volume name, to update the dmg design on Jenkins.
:m:
=> [DMG] design, path of volume

RELEASE_NOTES.txt
Add some changes from MUSIC 2.4 to MUSICardio 3.0. Do not hesitate to tell me if i forgot something, or if you want a line to be changed.
:m:
=> [ReleaseNotes] add musicardio3.0 changes

src/cmake/module/add_external_resources.cmake, src/layers/legacy/medCoreLegacy/medExternalResources.h, src/layers/legacy/medUtilities/medUtilities.cpp, src/layers/legacy/medUtilities/medUtilities.h, src/layers/medPython/base/conversion/medPythonConversionUtils.h, src/layers/medPython/base/conversion/medPythonQListConversion.h, src/layers/medPython/base/medPythonExport.h, src/layers/medPython/base/objects/medPythonModule.h, src/layers/medPython/cmake/embed_python.cmake, src/layers/medPython/cmake/python_files_info_win.cmake, src/layers/medPython/tools/bindings/medInria/header.i, src/layers/medPython/tools/bindings/qt/object.i, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, superbuild/projects_modules/medInria.cmake
Get lastest commit from medInria, specially Paint debug (https://github.com/medInria/medInria-public/pull/971)
:m:
=> [Sync2022-03] Paint debug deviceRatio

src/CMakeLists.txt
This is needed to compile the master branch.
=> Force USE_PYTHON OFF

src/app/medInria/areas/homepage/medHomepageArea.cpp
Link to the new MUSICardio website for 3.0.
:m:
=> [Help] link to musicardio documentation website

src/app/medInria/medMainWindow.cpp, src/cmake/module/set_lib_install_rules.cmake, src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp, src/layers/legacy/medImageIO/itkDataImageWriterBase.cpp, src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointProcess.cpp, src/plugins/legacy/iterativeClosestPoint/iterativeClosestPointToolBox.cpp, src/plugins/legacy/iterativeClosestPoint/medICPFilter.cxx, src/plugins/legacy/iterativeClosestPoint/medICPFilter.h, src/plugins/legacy/itkDataImage/readers/itkGDCMDataImageReader.cpp, src/plugins/legacy/itkDataSHImage/readers/itkDataSHImageReader.cpp, src/plugins/legacy/itkDataSHImage/writers/itkDataSHImageWriterBase.cpp, src/plugins/legacy/itkDataTensorImage/readers/itkDataTensorImageReaderBase.cpp, src/plugins/legacy/itkDataTensorImage/writers/itkDataTensorImageWriterBase.cpp, src/plugins/legacy/medVtkFibersData/readers/medVtkFibersDataReader.cpp, src/plugins/legacy/medVtkFibersData/writers/medVtkFibersDataWriter.cpp, src/plugins/legacy/vtkDataMesh/readers/vtkDataMesh4DReader.cpp, src/plugins/legacy/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp, superbuild/patches/VTK.patch
Get last updates from medInria3.2.x, including a debug on linux OS to compile, ICP changes and accents fix.
:m:
=> [Sync2022-09-20] ICP, accents

RELEASE_NOTES.txt
Update the release notes for 3.0 of MUSICardio.
:m:
=> [Release_notes] rm navigation wkspace, add debugs

packaging/apple/settings.json
Needed update for dmg on MUSICardio when we change the version number.
:m:
=> [MacOS] update version number for MSC dmg

src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp, src/layers/legacy/medVtkDataMeshBase/vtkMetaDataSetSequence.h, src/plugins/legacy/meshMapping/meshMappingToolBox.h
Same work as on https://github.com/medInria/medInria-public/pull/1079
Fix some differences on MUSICardio with medInria, to avoid complication during synchro, and avoiding to forgot debugs/enhancement code on one side.
:m:
=> [medToMSC] solves some mini differences with medInria3.4

superbuild/projects_modules/music-plugins.cmake
=> add pyncpp to music-plugins external project

superbuild/projects_modules/music-plugins.cmake
Switch to dedicated branch on music-plugins for v3.3.2.
:m:
=> [v3.3.2] branch music plugins v3.3.0 not master

src/app/medInria/main.cpp
Add the python plugin path (where bindings libraries will be found) to sys.path.
=> Add Python plugin path

src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
=> [polygonRoi] processOutput returned nullptr

src/layers/legacy/medImageIO/medInrimageImageIO.cpp, src/plugins/legacy/itkINRDataImageWriter/itkINRDataImageWriter.cpp
Synchro PR from https://github.com/medInria/medInria-public/pull/1166 on medInria.
=> workaround for Inrimage exporting on 3.4 --sync

src/plugins/legacy/reformat/medCropToolBox.cpp
From PR https://github.com/medInria/medInria-public/pull/1164 on medInria.
=> [medCropToolBox] fix error return value --sync

src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDatabaseSettingsWidget.cpp
Synchro PR from medInria: https://github.com/medInria/medInria-public/pull/1149
:m:
=> [Settings] solve graphical bug of database widget --sync

src/app/medInria/main.cpp, src/app/medInria/medSplashScreen.cpp, src/app/medInria/medSplashScreen.h
Synchro PR from medInria: https://github.com/medInria/medInria-public/pull/1145
:m:
=> [SplashScreen] speeds up launch removing txt on splashscreen --sync

src/layers/legacy/medCoreLegacy/data/medAbstractData.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.cpp, src/layers/legacy/medCoreLegacy/gui/toolboxes/medActionsToolBox.h
Synchro from this PR on medInria: https://github.com/medInria/medInria-public/pull/1144
:m:
=> [Thumbnail] 3.4, add a setting to [de]activate thumbnail generation --sync

src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
From PR https://github.com/medInria/medInria-public/pull/1135 on medInria to here.
:m:
=> [VTK] avoid med crash with wrong version of vtk files --sync

src/app/medInria/medLogger.cpp
Synchro from PR https://github.com/medInria/medInria-public/pull/1117 on medInria to here on MUSICardio.
:m:
=> [MemoryLeak] medLogger TeeStreams, TeeDevices and d --sync

src/app/medInria/areas/homepage/medHomepageArea.cpp
From PR https://github.com/medInria/medInria-public/pull/1116 on medInria.
:m:
=> [MemoryLeak] homepage widgets --sync

RELEASE_NOTES.txt
Synchro PR from this medInria PR https://github.com/medInria/medInria-public/pull/1169
:m:
=> [3.4] update release notes with current enhancement --sync

doxygen.conf
This PR changes the MUSICardio version number on the Doxygen conf file.
:m:
=> [Doxygen] change version number for doxygen project

src/layers/legacy/medCoreLegacy/parameters/medAbstractParameterL.cpp, src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.cpp, src/layers/legacy/medCoreLegacy/parameters/medDoubleParameterL.h, src/layers/legacy/medCoreLegacy/parameters/medParameterPoolL.cpp, src/layers/legacy/medCoreLegacy/parameters/medTimeLineParameterL.cpp, src/layers/legacy/medCoreLegacy/parameters/medTimeLineParameterL.h, src/layers/legacy/medCoreLegacy/views/navigators/medAbstractImageViewNavigator.cpp, src/layers/legacy/medCoreLegacy/views/navigators/medAbstractNavigator.cpp, src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp
This PR fixes a crash:
* Open a 4D data in a view, then a 3D mask/data
* Close the application -> crash
Parameter label was not well removed.
:m:
=> [Close] 4D+3D data in view crash at app closing

src/app/medInria/areas/homepage/medHomepageArea.cpp, src/app/medInria/medApplication.cpp, src/app/medInria/medMainWindow.cpp
In order to have a MUSICardio splash screen not too large and homepage logo not cropped, this PR adapts their sizes.
:m:
=> [Size] adapt logo and minimum application sizes

src/app/medInria/main.cpp
Avoid crash if something goes wrong during Python setup.
=> Catch Python exceptions on startup

src/layers/legacy/medVtkInria/medClutEditorToolBox/medClutEditorToolBox.cpp
Fix https://github.com/Inria-Asclepios/music/issues/939 which has been found also by Kévin on the current version. The view is updated when a vertex changes.
:m:
=> [ClutEditor] render the view to update threshold

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx, src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp
Fix https://github.com/Inria-Asclepios/music/issues/1065
This PR solves the 3d mode which was not by default at... Default, and was an hidden Raytracing and not GPU as displayed.
:m:
=> [3D] mode by default to Default, also on mac

RELEASE_NOTES.txt
Add some enhancement/debug in the release notes. This can be updated.
:m:
=> [Release Notes] add changes for msc 4.0

superbuild/CMakeLists.txt
see https://github.com/LIRYC-IHU/pyncpp/pull/19
=> fix openssl issue on macos

superbuild/projects_modules/music-plugins.cmake
I forgot to change back the path in my PR before merging it.
:m:
=> [plugins] forget to change back path

RELEASE_NOTES.txt
To be used with https://github.com/Inria-Asclepios/music/pull/1092
Update release notes.
:m:
=> [ReleaseNotes] update 4.0.6 for pipeline closing layers

RELEASE_NOTES.txt
Based on https://github.com/Inria-Asclepios/medInria-public/pull/864
COMMIT https://github.com/Inria-Asclepios/medInria-public/commit/30e822946d40998b7015262e13862023d308b8f6
To be used with https://github.com/Inria-Asclepios/music/pull/1095
:m:
=> [Histo] release notes for fix of non-manual algos

RELEASE_NOTES.txt
Based on https://github.com/Inria-Asclepios/medInria-public/pull/865
COMMIT https://github.com/Inria-Asclepios/medInria-public/commit/626d7e71d29a50cc7b95f67c7ddd3810747e9da3
Add Carto debug https://github.com/Inria-Asclepios/music/pull/1096 in release notes
:m:
=> [4.0.6] carto fix on release notes

src/CMakeLists.txt
Small version change to update the soft description.
:m:
=> [4.0.7] changes of version number for description

.github/workflows/musicardio-macos.yml, RELEASE_NOTES.txt, src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp, src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h, src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp, src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp, src/layers/legacy/medImageIO/itkDataImageReaderBase.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemons.cpp, src/plugins/legacy/LCCLogDemons/LCCLogDemons.h, src/plugins/legacy/LCCLogDemons/LCCLogDemonsToolBox.cpp, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.cpp, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemons.h, src/plugins/legacy/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp, src/plugins/legacy/manualRegistration/manualRegistration.cpp, src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp, src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp, src/plugins/legacy/polygonRoi/toolboxes/defaultLabelToolBox.cpp, src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp, src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h, src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.cpp, src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.h, src/plugins/legacy/polygonRoi/viewevent/defaultViewEvent.cpp, src/plugins/legacy/voiCutter/voiCutterToolBox.cpp, superbuild/projects_modules/medInria.cmake
Synchronization of 4.1 branch (~dev) with bug fixes from master branch (4.0.3 to 4.07).
Originally validated on https://github.com/Inria-Asclepios/medInria-public/pull/876, i recreate this PR to be able to rebase it.
:m:
=> [Synchro] branch 4.1 (dev) receives bugfix from 4.0.3 to 4.0.7

src/app/medInria/main.cpp, src/layers/legacy/medCoreLegacy/database/medDataManager.h
Fix https://github.com/Inria-Asclepios/music/issues/1105
From an idea of @fcollot 
This PR seems to fix a crash at the ending of the app with a pipeline opened.
Tested on Ubuntu. Indeed the garbage collector is called at closing if a pipeline was opened.
:m:
=> [Closing] garbage collector for pipeline at ending
