app/medInria/main.cpp
src/medCore/database/medDataManager.cpp

Try to load different files (.mha, .dcm, folders of .dcm) with and without an accent in their paths.
This PR should make it work.
PS: the method I am using (QTextCodec::setCodecForCStrings) doesn't exist anymore in qt5, I trust @mikejbuckingham and the medInria guys to find a solution.

[encoding] allows to load files whose path contains accents

---

src/medCore/database/medDataManager.cpp

From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/16 
The default thumbnail was wrong. The fact that this particular image gives the default thumbnail can be studied also in a future PR.
:m:

[thumbnail] wrong pixmap location

---

src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp

This PR solves this issue: https://github.com/Inria-Asclepios/music/issues/254
> When using the MUSIC paint segmentation toolbox, a new layer is created representing the painted mask. This layer is not cleared when the user chooses to close it, i.e. the previous painted area is still there.
> Shouldn't closing the layer result in the deletion of the buffered mask data ?
> 
> Steps to reproduce this behavior:
> 1 - open any image data in segmentation workspace
> 2 - using MUSIC paint algorithm, paint whatever on the image
> 3 - close the layer called 'no name'
> 4 - paint again somewhere else on the image
> 5 - the layer called 'no name' is back, with the previous painted area.
> 
> To me closing the layer should do something akin to the button 'Clear Mask'.
:m:

[mscPaint] clear after rm of noName

---

src-plugins/itkDataImage/writers/itkMetaDataImageWriter.cpp

Third point of https://github.com/Inria-Asclepios/music/issues/242
The user did not see anymore the mha extension on export pop-up. This PR allows to show mha and mhd together.
NB: .mha files are made of one file, and mhd files are made of 1 header file and 1 raw file.
:m:

[dataImageWriter] add mha by default on export

---

app/medInria/medSegmentationWorkspace.cpp
app/medInria/medSegmentationWorkspace.h
src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp
src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.h
src/medCore/gui/toolboxes/medSegmentationAbstractToolBox.h
src/medCore/gui/toolboxes/medSegmentationSelectorToolBox.cpp
src/medCore/gui/toolboxes/medSegmentationSelectorToolBox.h

In Histogram, VoiCutter, VariationalSeg, polygonROI and CoronarySeg, you had a `Object::connect: No such signal polygonRoiToolBox::installEventFilterRequest(medViewEventFilter*)` warning, as see at third point of this issue: https://github.com/Inria-Asclepios/music/issues/91
The only toolbox which had this signal was mscPaint (and Paint, but it's going to be removed), so i moved it in medSegmentationAbstractToolBox where other tlbx could access if needed.

[SegmentationWorkspace] move signal events in mscPaint

---

src-plugins/medClut/medClutToolBox.cpp
src-plugins/medClut/medClutToolBox.h
src-plugins/reformat/reformatToolBox.cpp
src-plugins/reformat/reformatToolBox.h

As in https://github.com/Inria-Asclepios/music/pull/259/files on medProjectionMapping
This PR uses medToolBox::setWorkspace(workspace); in Clut and ReformatToolBox.
:m:

[getWorkspace] Clut & Reformat

---

src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/gui/toolboxes/medToolBox.h
src/medCore/medJobItem.h
src/medCore/process/medAbstractProcess.cpp
src/medCore/process/medAbstractProcess.h
src/medCore/process/medRunnableProcess.cpp
src/medCore/process/medRunnableProcess.h

This PR allows to standardize a bit our data error messages.
`description()` is defined in the specific process and is going to be the name of the process.
(Thx @fcollot for the translation of the error messages ^^)
:m:

[medAbstractProcess] add mesh and volume error messages

---

src/medUtilities/medUtilities.cpp
src/medUtilities/medUtilities.h

A PhD student here wanted to use the mesh manipulation tbx:
she dropped a volume (as a reference to re-position the mesh) then a mesh. After that, when you click on the tbx, it all switches to VR, which is very sloooow with volumes.
That's why I changed `medUtilities::switchToVR()` to `medUtilities::switchTo3D`, and adds a second parameter, a Qstring defining the 3dMode (default: VR).
It implies changes in music-plugins and medInria-private

[medUtilities] decide which mode when switching to 3d

---

src/medCore/gui/commonWidgets/medSlider.cpp
src/medCore/gui/commonWidgets/medSlider.h

When clicking on the bar of the slider, this one moves incrementally: if you click at the left extremity of the bar, the slider will move on step to the left ... You get the idea.
With this PR, the slider jumps where you click.
It is appreciated when changing the slice.
Note: medSlider is only used inside medIntParameters, so you know where to do the tests. (I will see if I can use medSlider in more cases)

[medSlider] Where you click is where you get

---

src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp

Reminder: instead of QComboBox, medComboBox can only be scrolled when it has focus, it prevents annoying behaviours when scrolling down a toolbox.

[ICP] uses medComboBox (tiny)

---

app/medInria/medSegmentationWorkspace.cpp
src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.h
src-plugins/manualRegistration/manualRegistrationToolBox.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.h
src-plugins/medClut/medClutToolBox.cpp
src-plugins/medClut/medClutToolBox.h
src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp
src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.h
src-plugins/reformat/medCropToolBox.cpp
src-plugins/reformat/medCropToolBox.h
src-plugins/reformat/reformatWorkspace.cpp
src-plugins/reformat/resliceToolBox.cpp
src-plugins/reformat/resliceToolBox.h
src/medCore/gui/medAbstractWorkspace.cpp
src/medCore/gui/toolboxes/medDiffusionSelectorToolBox.cpp
src/medCore/gui/toolboxes/medFilteringSelectorToolBox.cpp
src/medCore/gui/toolboxes/medSegmentationAbstractToolBox.h
src/medCore/gui/toolboxes/medSegmentationSelectorToolBox.cpp
src/medCore/gui/toolboxes/medSegmentationSelectorToolBox.h
src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/gui/toolboxes/medToolBox.h

I tried to work on this issue: https://github.com/Inria-Asclepios/medInria-public/issues/34
> We should remove all the calls to  ```medToolBox::setWorkspace ``` and do it directly in ```medAbstractWorkspace::addToolBox ```.
For now, this is the only way i found to use the toolboxes from the Segmentation workspace.
Working also with the Reformat workspace.
(I'll be in holiday tomorrow, and monday/tuesday of the next week)

[workspace] init not in tlbx

---

src/medCore/gui/medAbstractWorkspace.cpp

In Layer settings, when you removed the last layer, there was an empty data displayed on the view. This PR allows to clean and remove the view when there is no data left on the view. I removed also the call to 
`updateLayersToolBox()` because it's automatically done.
:m:

[medAbstractWorkspace] rm last layer removes also the view

---

src-plugins/vtkDataMesh/readers/vtkDataMeshReader.cpp
src-plugins/vtkDataMesh/readers/vtkDataMeshReader.h
src-plugins/vtkDataMesh/writers/vtkDataMeshWriter.cpp
src-plugins/vtkDataMesh/writers/vtkDataMeshWriter.h
src/medImageIO/itkDataImageReaderBase.cpp
src/medImageIO/itkDataImageReaderBase.h
src/medImageIO/itkDataImageWriterBase.cpp
src/medImageIO/itkDataImageWriterBase.h

**Requires https://github.com/Inria-Asclepios/medInria-public/pull/51 to work**
This PR adresses two problems (see https://github.com/Inria-Asclepios/medInria-public/issues/46)
- The reader/writer for VTK files stores metadata in the header, but this header is limited to 256 characters.
- The readers/writers for VTK and ITK files do not store all the metadata.
For VTK I stored the metadata as field data for all cases (except CARTO which is handled by a different writer). In the reader I had to make it "backwards-compatible" since the previously written files will have the metadata in the header. Therefore the reader does the following:
- It firsts checks if metadata is present in the field data and loads it.
- If the first attempt failed, it tries to take the metadata from the header …

Metadata writing/reading for VTK and ITK

---

src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp
src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.h

In Segmentation workspace, drop an image, select MUSIC Paint Seg, "Paint/Erase" and try to draw something, it crashes.
Note: if you set the toolbox, then drop the image, it doesn't crash.
After selecting the toolbox, this latter is not aware of what's inside the view, so we need to let it know.
Selecting the toolbox calls the method `show()` of the Paint Toolbox. 
`showEvent()` is called every time `show()` is called, so I just reimplemented it to call `updateView()`.
In the end, every time we show the toolbox, we acknowledge the state of the view.

[Paint] udpateView called if show is called on the tbx

---

src/medCore/database/medDatabaseModel.cpp
src/medCore/database/medDatabaseRemover.cpp
src/medCore/database/medDatabaseRemover.h

Found through this issue: https://github.com/Inria-Asclepios/medInria-public/issues/16
Cf this issue: https://github.com/Inria-Asclepios/medInria-public/issues/24
We update in medDatabaseModel the thumbnail location in the moved data.
In medDatabaseRemover we check the thumbnail location of the patient/study/etc removed.
:m:

[database] move-remove data-thumbnail

---

app/medInria/medRegistrationWorkspace.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.cpp

As posted [here](https://github.com/Inria-Asclepios/medInria-public/issues/55#issuecomment-221528501), with Manual registration, when you slice on one view, it automatically slices on the other one; which is not very convenient when you try to register to data.
This behaviour has been noticed in the VT pipeline, but appears as well in the Registration workspace.
It's simple, the different views are linked in many ways including in position/slicing.
By removing the linking in position and slicing in manual registration and in the registration workspace.

[Manual registration] Proper linking of the different views

---

src-plugins/manualRegistration/manualRegistrationLandmark.cpp
src-plugins/manualRegistration/manualRegistrationLandmarkController.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.cpp

Debug on https://github.com/Inria-Asclepios/medInria-public/pull/4
> Open data -> Start Segmentation -> add landmarks -> Close a view (with the X button)
> You will have a seg fault in `manualRegistrationLandmark::~manualRegistrationLandmark()` at `View->RemoveObserver(SeedCallback);`
I wanted also to refresh the views after a Reset() with something like `static_cast<medVtkViewBackend*>(d->leftContainer->view()->backend())->view2D->Render();` but did not succeed right now, and it was not an emergency.
:m:

[manualRegistration] debug linux view reset

---

app/medInria/medHomepageArea.cpp

On the main page of the software, we have columns: `Basic`, `Methodology`, `Clinical` and `Other`.
The PR allows to hide any of these columns if empty.
:m:

[medHomepageArea] hide column if empty

---

src-plugins/reformat/medCropToolBox.cpp

Reformat workspace, open an image; create a new tab, drop another image in the view.
Use the cropping tool, "Apply". Nothing happens in the current view, go back to the first tab and you 'll see the result of your crop.
It opens the output of the crop in the current tab.

[Crop] displays output in the current tab

---

src-plugins/itkFilters/itkFiltersToolBox.cpp

Issue: https://github.com/Inria-Asclepios/medInria-public/issues/63
> In `itkFiltersToolBox::itkFiltersToolBox(blabla)`
> 
> "Add Constant to Image" -> "Add _constant_ to image"
> "Substract Constant from Image" -> "_Subtract_ _constant_ from image"
> 
> We can also remove "filter" from the next lines.
In fact, just this commit: https://github.com/Inria-Asclepios/medInria-public/commit/cb667ecab69e18d84ad1f0e3093217220aab3e6c
:m:

[itkFilters] correct spelling

---

src-plugins/itkN4BiasCorrection/itkN4BiasCorrectionToolBox.cpp
src-plugins/medBinaryOperation/medBinaryOperationToolBox.cpp
src-plugins/medMaskApplication/medMaskApplicationToolBox.cpp

From https://github.com/Inria-Asclepios/medInria-public/issues/88
```
These toolboxes progress bars do not change during the process computation:
* N4 bias
* binaryOperation
* maskApplication
```
-> progress bar activated.
_PS: there are 2 types of activation. You can look at the way mscSuperResolutions handle that._
:m:

[progressBar] activate bar in N4, binaryOpe and maskApplication

---

src-plugins/reformat/medCropToolBox.cpp

From https://github.com/Inria-Asclepios/medInria-public/issues/14
Do not allow Crop container to be splittable.
:m:

[medCropToolbox] container can't be split

---

app/medInria/medFilteringWorkspace.cpp
src-plugins/itkFilters/itkFiltersToolBox.cpp
src-plugins/itkFilters/itkFiltersToolBox.h

From https://github.com/Inria-Asclepios/medInria-public/issues/89
Same system as in medMeshingWorkspace, the toolbox is updated when a data is put into an input container.
:m:

[IntensityWindowing] put back update() fct

---

src-plugins/reformat/resliceToolBox.cpp
src/medCore/gui/medTabbedViewContainers.cpp
src/medCore/gui/medTabbedViewContainers.h

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/134
Provide two functions in `medTabbedViewContainer`. The first one returns the first selected container, and the second one its view. This allows to get directly the view with "getWorkspace()->stackedViewContainers()->getFirstSelectedContainerView();" as you can see in the example.
I wanted to see that with you before changing every toolbox in MUSIC ^^.
:m:

[medTabbedViewContainer] add function to get first container and view

---

src-plugins/manualRegistration/manualRegistrationLandmark.cpp
src-plugins/manualRegistration/manualRegistrationLandmarkController.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.h

Solves:
- memory leak https://github.com/Inria-Asclepios/medInria-public/issues/13,
- refresh views after a Reset to remove the display of landmarks https://github.com/Inria-Asclepios/medInria-public/issues/13,
- Reset then Close actions do not crash,
- no space before ":" in English,
- Reset disables the Compute button,
- Reset then scroll crash is solved: https://github.com/Inria-Asclepios/medInria-public/issues/87
:m:

[manualRegistration] solves Reset bugs

---

app/medInria/medHomepageArea.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/128
```
On the Homepage, in the little text describing the project:
"MUSIC (X.Y.Y) is a software developed ..."
It would make discussion with users easier.
```
:m:

[homepage] add version number on frontpage

---

src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp
src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.h

From this issue about the closing part: https://github.com/Inria-Asclepios/medInria-public/issues/119
And this issue concerning the name: https://github.com/Inria-Asclepios/medInria-public/issues/114
When you use magic wand, remove only the original data and then use magic wand again, no more crash.
:m:

[mscPaint] change name, correct close by crossed button

---

app/medInria/main.cpp
app/medInria/medApplication.cpp
app/medInria/medApplication.h
app/medInria/medQtMessageHandler.cpp
app/medInria/medQtMessageHandler.h

After testing, I found out that many freezes we had were due to the management of qt messages (see https://github.com/Inria-Asclepios/medInria-public/issues/142, https://github.com/Inria-Asclepios/medInria-public/issues/148).
I noticed that these freezes appear when you call a process in a thread and this process launches a qMessage : e.g Gaussian filter, many mesh-related processes. 
Thanks to Flo's debug, I know that a thread is blocked in the *write()* method of dtkLogEnginePrivate.
My theory is that two threads are trying to write ate the same time with dtkLogger.
Make the process's thread emit a signal, caught in the main thread to let only the main thread deal with the dtkLogger.
So I created my own QtMessageHandler. This one is called every time a qMessage is used, it will then …

Qt messages handler

---

app/medInria/medApplication.cpp
app/medInria/medApplication.h
app/medInria/medQtMessageHandler.cpp
app/medInria/medQtMessageHandler.h

(fixes https://github.com/Inria-Asclepios/music/issues/382, replaces https://github.com/Inria-Asclepios/medInria-public/pull/162)
This PR fixes some of the issues we've had with log files:
* The log messages are sent by an asynchronous signal using char*, which leads to debug messages with strange characters because the data containing the message was trashed in memory. To fix this I had used a previous solution (https://github.com/Inria-Asclepios/medInria-public/pull/162) where I made the signal synchronous, which guaranteed that the message was being written before the data was trashed. This worked but introduced another bug: if the logger sends its own message during the process, it caused a recursion into the logging process which provoked a freeze. I dropped this idea and instead …

Fixed log loops and signal errors

---

app/medInria/main.cpp
app/medInria/medMainWindow.cpp

From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/143
boost streams were not closed at the closing of the application, creating a crash.
:m:

[logs] stops the app crash at closing

---

src-plugins/itkFilters/itkFiltersComponentSizeThresholdProcess.cpp

(solves https://github.com/Inria-Asclepios/music/issues/396)
The issue stems from an error in ```itkFiltersComponentSizeThresholdProcess``` where the return value of ```castToUInt``` is treated as a boolean, when in fact it's a DTK success/failure integer. In addition I found a syntax error, where a return statement wasn't properly removed. Also, debugging this made me realise that processes called directly from pipeline steps are not checked for errors. I made an issue for this (https://github.com/Inria-Asclepios/music/issues/397).

[ComponentSizeThreshold] return value of castToUInt is not a boolean

---

src-plugins/medMaskApplication/medMaskApplication.cpp

Part of the solution of https://github.com/Inria-Asclepios/music/issues/402
Drop a volume and a mask of different dimensions in Segmentation workspace, select Histogram Analysis, click on Create containers. The app crashes.
Inside the slot launched by this last click, the mask is applied to the image using the `medMaskApplication` process:
``` c++
medAbstractData* HistogramAnalysisToolBox::applyMaskToImage()
{
dtkSmartPointer<medAbstractProcess> maskProcess = dtkAbstractProcessFactory::instance()->createSmartPointer("medMaskApplication");
maskProcess->setInput(d->mask, 0);
maskProcess->setInput(d->image, 1);
maskProcess->setParameter(d->backgroundSpinBox->value(), 0);
maskProcess->update();
d->segmentedImage = maskProcess->output();
return d->segmentedImage;
}
```
this one is smart enough …

[maskAppl] output should be NULL until process successful update

---

src-plugins/manualRegistration/manualRegistrationToolBox.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.h

:D The last PR about switching between toolboxes (it's clearer for you to review several PR on dedicated toolboxes than a big one with everything in it). About this issue: https://github.com/Inria-Asclepios/music/issues/406
The manual registration tool is stopped if we switch.
:m:

[manualReg] switch to an other toolbox

---

src-plugins/reformat/resliceToolBox.cpp

From https://github.com/Inria-Asclepios/medInria-public/issues/174
Closing the tab/view should reset the toolbox.
When we close the tab, we call ```stopReformat```

[Reslice] closing the tab, stops the reslicing

---

src-plugins/medVtkView/medVtkViewNavigator.cpp

This PR removes annoying warnings in log when we switch a mesh to 3D:
```
ERROR - lun. nov. 7 15:58:58 2016 - ERROR: In /home/mathildemerle/Dev/medinria-superproject/VTK/Filtering/vtkDemandDrivenPipeline.cxx, line 727
vtkStreamingDemandDrivenPipeline (0x52e0580): Input port 0 of algorithm vtkOpenGLImageSliceMapper(0x280c000) has 0 connections but is not optional.
```
:m:

[Logs] rm 3D rendering warning on mesh

---

src-plugins/reformat/resliceToolBox.cpp
src-plugins/reformat/resliceToolBox.h

_Will be rebased with https://github.com/Inria-Asclepios/medInria-public/pull/177_ --> REBASE DONE
From (and maybe last PR) from https://github.com/Inria-Asclepios/music/issues/406
Switching to an other PR stop the segmentation of Reslice (and display the original dataset).
:m:

[Reslice] solve switch to other toolbox

---

src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp

Fixes #115 
Problem:
First stroke of paint causes the creation of a new data, that is then added as a layer. This caused, through a series of method calls, the re-instanciation of a new event view filter, therefore losing the current painting status.
The user was forced to click a second time to continue segmenting.
Proposed solution:
Instanciate the event filter once and for all.

[mscPaintAlgo] Fix first stroke of paint toolbox.

---

src-plugins/itkDataImage/interactors/medVtkViewItkDataImageInteractor.cpp

see https://github.com/Inria-Asclepios/medInria-public/issues/192
The problem was caused by a loop in the slots being called.

[medVtkViewItkDataImageInteractor] fixes scroll bug in 4-window view

---

app/medInria/medFilteringWorkspace.cpp
app/medInria/medRegistrationWorkspace.cpp
app/medInria/medVisualizationWorkspace.cpp
app/medInria/medVisualizationWorkspace.h
src/medCore/gui/medAbstractWorkspace.cpp

From https://github.com/Inria-Asclepios/music/issues/356
This PR locks tab in Meshing, Reformat and Segmentation.
:m:

[Tab] lock tab by default in the application

---

src/medCore/data/medAbstractDataWriter.h
src/medCore/database/medDataManager.cpp
src/medCore/database/medDataManager.h
src/medCore/database/medDatabaseExporter.cpp
src/medCore/database/medDatabaseExporter.h

The specificity of exporting a scene into NavX format is that you save several datasets into one single file (an xml). Which is hardly doable in the app right now: a ```dtkAbstractDataWriter``` only accepts one single ```medAbstractData*```.
I added in the core, a new class ```medAbstractDataWriter``` which inherits from ```dtkAbstractDataWriter``` and possesses a method allowing to have a list of ```medAbstractData``` as input.
The NavX writer will then inherit from this class.
({Probably giving a list of datasets will be profitable for other writers as well)

[NavX] Adds the possibility to export a list of data

---

src-plugins/manualRegistration/manualRegistrationToolBox.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.h
src-plugins/reformat/medCropToolBox.cpp
src-plugins/reformat/medCropToolBox.h
src-plugins/reformat/resliceToolBox.cpp
src-plugins/reformat/resliceToolBox.h
src/medCore/gui/toolboxes/medAbstractSelectableToolBox.h
src/medCore/gui/toolboxes/medSelectorToolBox.cpp

Following https://github.com/Inria-Asclepios/medInria-public/pull/201
Adapt manual registration, cropping and reslice to the switch between toolboxes.
(will be rebased)
:m:

[manualReg+Crop+Reslice] switch to changeSelectedToolBoxEvent

---

src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp
src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.h

Begin to solve problems switching from toolbox to other tlbx: https://github.com/Inria-Asclepios/music/issues/406
This PR solves data removing problems in Paint:
( these 3 points call the `initializeToolBox` function)
* when the user removes directly the additional mask, it doesn't remove the original data set, and the toolbox is initialized;
* when the user removes directly the original data set, the toolbox is initialized;
* when we switch to an other toolbox, the additional (mask) data is removed and the toolbox is initialized.
:m:

[Paint] solve problem switching to other tlbx or rm datasets

---

src/medCore/gui/medAbstractWorkspace.cpp
src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/gui/toolboxes/medToolBox.h

From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/212
`medToolBox::clear()` only called `medToolBoxBody::clear()`. This function is used in `medAbstractWorkspace.cpp` only. So, in this file, now, we directly call `medToolBoxBody::clear()`. `medToolBox::clear()` becomes empty (and was already virtual). In this way, `medToolBox::clear()` is called by toolboxes which don't need to do a dedicated clear function. So, we do not need to change anything in toolboxes.
:m:

[Switch] medToolBox clear is ... cleared

---

app/medInria/medLogger.cpp
app/medInria/medLogger.h

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/166
Will be rebased with https://github.com/Inria-Asclepios/medInria-public/pull/178
Add a `medLogger::truncateLogFileIfHeavy()` function in `medLogger::medLogger()` which allow to check the size of the log file at launching of the app, and truncate it if needed (old lines are discarded).
:m:

[logs] truncate heavy log file

---

src/medCore/database/medDatabaseController.cpp
src/medCore/database/medDatabaseRemover.cpp

From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/222
In the database directory, with this PR, ref.png files are realy removed when their dataset is removed.
:m:

[DB] rm datasets remove ref.png

---

src-plugins/manualRegistration/manualRegistrationToolBox.cpp

Cf. this issue https://github.com/Inria-Asclepios/music/issues/443
We don't want to split views in the registration step of pipelines.
:m:

[Registration] do not allow to split container in pipeline

---

src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp

From this issue https://github.com/Inria-Asclepios/music/issues/343
Following this PR https://github.com/Inria-Asclepios/music/pull/450
Solves crash in pipelines if users click on Next on an undone Paint step.
:m:

[Paint] remove a crash in pip if Next on undone step

---

src/medCore/gui/database/medDatabaseView.cpp
src/medUtilities/statsROI.cpp

A small Pull Request to remove some warning in medInria-public concerning comparison between `unsigned int` and `int` values.
:m:

[statsROI-metabaseView] comparison between unsigned int and int

---

src/medCore/database/medDatabaseController.cpp
src/medCore/database/medDatabaseImporter.cpp
src/medCore/database/medDatabaseRemover.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/231
Moving and/or deleting a serie/study/patient handle ref.png, its directory, and the patient directory if needed.
After each `removeThumbnailIfNeeded` we check if the ref directory is empty, or the patient one.
[A so much clean database...](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.factinate.com%2Fwp-content%2Fuploads%2F2017%2F01%2FFantasia-Broom.gif&f=1)  :)
:m:

[DB] remove old study after moving its series does not rm thumb

---

src-plugins/manualRegistration/manualRegistrationLandmark.cpp
src-plugins/manualRegistration/manualRegistrationLandmarkController.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.cpp

From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/150
CTRL is already used to select view in medInria/MUSIC, we can't use it for something else, as the deletion of landmarks in manual registration.
I switched the landmark removal to the "BackSpace" button, updated both views afterwards, and added and explaination for users.
:m:

[manualRegistration] delete landmark behavior solved

---

src-plugins/reformat/medCropToolBox.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/260
The crop box is in green, allowing to see the widget over a white image.
:m:

[crop] border widget in green

---

src-plugins/itkFilters/itkMorphologicalFiltersProcessBase.cpp
src-plugins/itkFilters/itkMorphologicalFiltersProcessBase.h
src-plugins/itkFilters/itkMorphologicalFiltersProcessBase_p.h
src-plugins/itkFilters/itkMorphologicalFiltersToolBox.cpp

The new algorithm to generate the thinning meshes requires different morphological filtering kernel shapes (ball, cross and box). I added this possibility in the process and toolbox.
I also activated the parametric mode of the structuring element. This makes the ball kernel more accurate as indicated in the ITK doc:
> Setting this flag to true will use the parametric definition of the object and will generate structuring elements with more accurate areas, which can be especially important when morphological operations are intended to remove or retain objects of particular sizes. When the mode is turned off (default), the radius is the same, but the object diameter is set to (radius*2)+1, which is the size of the neighborhood region. Thus, the original ball and annulus structuring elements …

[morpho filters] added kernel shape

---

src/medCore/gui/commonWidgets/medSlider.cpp

Needed for https://github.com/medInria/medInria-private/pull/139
Problem occured with multiple datasets, a ROI, and if you deleted the first dataset.
:m:

[medSlider] handle tick list error when empty

---

app/medInria/medRegistrationWorkspace.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/144
`addImpactedView` is not used in the other workspaces, and i did not see any changes removing these 2 lines. In addition, these views are already set in `medAbstractWorkspace::addViewstoGroup`.
This removal allows to avoid the displayed pop-up when you switch a dataset from 2D to 3D in registration views.
:m:

[registrationWorkspace] rm pop-up when switch from 2d to 3d

---

src/medImageIO/itkDCMTKImageIO.cpp

Resolves https://github.com/Inria-Asclepios/medInria-public/issues/276.
In the previous code, slice location was forced to follow the linear function : 
```sliceLocation = coef * z-spacing```
Of course it should be an affine function:
```sliceLocation = firstSliceLocation + coef * z-spacing```
That's what I did, trying to put it simply.
I also removed a useless variable.
Since it's quite a critical change, I encourage the reviewers to test it by loading several DICOM folders. For instance if you have DICOM sequences ...

Slice Location re-definition

---

src/medCore/gui/viewContainers/medViewContainer.cpp
src/medCore/gui/viewContainers/medViewContainer.h

From this issue https://github.com/Inria-Asclepios/music/issues/399 ("Imported scene has anonymous data")
It allows to keep patient name, patient ID, birthdate, gender, and create a dedicated "Scene" study description. If you save this loaded scene, it will be stored in the original patient tree.
Example:
```xml
<!DOCTYPE xml>
<scene>
<layeredView path="view{81bfdeb6-aabd-4747-9630-d95bd6fdc056}/mapping.xml" id="medVtkView"/>
<patient gender="M" patientID="cc6405a1-5f69-416c-a13d-f21b36514d19" birthDate="19500929" studyDescription="Scene" patientName="Belzebuth"/>
</scene>
```
I save the patient information in the `globalMapping.xml` file, as an independent `QDomElement`. @LoicCadour we'll have to check if it's ok on the Web Viewer.
Works on scene, and from the "Export to Viewer" button …

[medViewContainer] scene, allow to keep patient info

---

src/medCore/gui/toolboxes/medSelectorToolBox.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/291
This PR sorts alphabetically the toolboxes names in the medSelectorToolBox combobox.
(One-line PR)
:m:

[medSelectorToolBox] sort alphabetically toolboxes names

---

src-plugins/iterativeClosestPoint/iterativeClosestPointProcess.cpp
src-plugins/iterativeClosestPoint/iterativeClosestPointProcess.h
src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp

From https://github.com/Inria-Asclepios/medInria-public/issues/293
I adapted the setParameter types to the values type. Here also, there is no widget using long long, but as we used to, we don't use the `frame` parameter, and we use `channel`.
:m:

[ICP] setParameter better data type

---

src-plugins/itkFilters/itkFiltersShrinkProcess.cpp
src-plugins/itkFilters/itkFiltersShrinkProcess.h
src-plugins/itkFilters/itkFiltersToolBox.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/294
This PR avoids a useless conversion in `tkFiltersToolBox::setupItkShrinkProcess()` using `int` instead of `double` (`int` is the type returned by the QSpinBox).
It has a more important use: in the pipelines, the user is going to use `int` instead of `double` (which was not instinctive because the Shrink toolbox display `int` values).
:m:

[Shrink] setParameter better data type

---

src/medCore/data/medMetaDataKeys.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/288
The dicom metadata concerning the age of the patient is not always a number, it can look like: "032Y". In fact, it can change from a MR/CT constructor to another. 
This PR displays the actual age given by the dicom (as a string).
:m:

[Browser] lost metadatakey age displayed

---

src/medCore/database/medAbstractDatabaseImporter.cpp

From https://github.com/Inria-Asclepios/medInria-public/issues/285 (I copy-pasted the text, but check for comments)
When importing the CT or MR, each slice becomes a a file in the db, i.e MUSIC cannot generate the volume.
These dcm data don't have a *SeriesDescription* tag, which is used to generate a VolumeID. And as the ```medAbstractDatabaseImporter``` code says:
> // 2.3) Generate an unique id for each volume
// all images of the same volume should share the same id
When MUSIC can't find the *SeriesDescription* tag, it sets to the filename; which is annoying because : 1 slice = 1 file = 1 VolumeID.
When there is no *SeriesDescription* tag, we have to set the series description to something that can always be found and that exclusively describes the series.Like a required tag …

when no SeriesDescription use Series Instance UID

---

src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemons.cpp
src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsToolBox.cpp
src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/process/medAbstractProcess.h

Following this old issue: https://github.com/Inria-Asclepios/medInria-public/issues/60
This toolbox wasn't working because: 
* the cast filter wasn't done in case of datasets not in `double` or `float`,
* we needed to resample datasets to have the same spacing, etc, before the registration method.
:m:

[diffeoDemon] solve physical space failure

---

app/medInria/medMainWindow.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/113
Small PR to remove the close button at bottom-right of the app. Indeed, it calls `medMainWindow::closeEvent` but the native close buttons are doing the same.
:m:

[close] no need of a close button

---

src/medCore/views/medAbstractLayeredView.cpp

From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/224
If you add 2 datasets in a view, and remove the first one, the opacity is not initialized on the remaining dataset. Solving this problem solved the issue crash on my side.
Pauline, Mehdi, tell me if it's ok now :)
:m:

[DataView] rm data: view was not re-initialized

---

RELEASE_NOTES.txt

One thing we did not do is to update the release notes for each release.
This PR adds the v2.0.0 notes, and the v1.1.2 notes (i took the informations on the release mail from the 04/04/2017).
If needed, we can still add commits here if we merge something interesting for a list like that.
I'm adding also this PR on this [how to validate a new release](https://github.com/Inria-Asclepios/music/wiki/How-to-validate-a-new-release) wiki page.
Note: do not forget to put milestone on PRs.
Added : " - Enhancement Help (?) buttons in the toolboxes headers"
And "- Add a unique progress bar for processes"
:m:

[RELEASE_NOTES] add MUSIC enhancement

---

app/medInria/medMainWindow.cpp

Reverts Inria-Asclepios/medInria-public#277
This poses an ergonomic problem as currently the mac menu bar does not show on fullscreen mode, forcing the user to exit fullscreen in order to quit the application which is very annoying.

Revert "[close] no need of a close button"

---

src-plugins/itkProcessRegistrationDiffeomorphicDemons/itkProcessRegistrationDiffeomorphicDemonsToolBox.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/313
1-line PR. Add the display of error message.
I think it should be merged on 2.0.0 since it's an error in a 2.0.0 PR.
:m:

[Diffeo] solve error not displayed

---

src/medImageIO/itkDCMTKImageIO.cpp

Partially adresses https://github.com/Inria-Asclepios/medInria-public/issues/318
This is needed for RGB DICOMS to be imported properly.

[itkDCMTKImageIO] Num components taken into account for slice size

---

src-plugins/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
src-plugins/iterativeClosestPoint/iterativeClosestPointToolBox.cpp
src-plugins/itkFilters/itkFiltersToolBox.cpp
src-plugins/itkFilters/itkMorphologicalFiltersToolBox.cpp
src-plugins/medBinaryOperation/medBinaryOperationToolBox.cpp
src-plugins/medMaskApplication/medMaskApplicationToolBox.cpp
src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/process/medRunnableProcess.cpp

Originally used in https://github.com/Inria-Asclepios/music/pull/489
This PR adds the `handleDisplayError` function by default in `medToolBox::addToolBoxConnections`
:m:

[medToolBox] handleDisplayError by default

---

src-plugins/itkDataImage/interactors/medVtkViewItkDataImage4DInteractor.cpp
src-plugins/vtkDataMesh/interactors/vtkDataMesh4DInteractor.cpp
src-plugins/vtkDataMesh/readers/vtkDataMesh4DReader.cpp
src-plugins/vtkDataMesh/readers/vtkDataMesh4DReader.h
src-plugins/vtkDataMesh/readers/vtkDataMeshReader.cpp
src-plugins/vtkDataMesh/readers/vtkDataMeshReader.h
src-plugins/vtkDataMesh/readers/vtkDataMeshReaderBase.cpp
src-plugins/vtkDataMesh/readers/vtkDataMeshReaderBase.h
src-plugins/vtkDataMesh/writers/vtkDataMesh4DWriter.cpp
src-plugins/vtkDataMesh/writers/vtkDataMesh4DWriter.h
src-plugins/vtkDataMesh/writers/vtkDataMeshWriter.cpp
src-plugins/vtkDataMesh/writers/vtkDataMeshWriter.h
src-plugins/vtkDataMesh/writers/vtkDataMeshWriterBase.cpp
src-plugins/vtkDataMesh/writers/vtkDataMeshWriterBase.h
src/medCore/views/medAbstractImageView.cpp
src/medVtkInria/vtkDataManagement/vtkMetaDataSet.h
src/medVtkInria/vtkDataManagement/vtkMetaDataSetSequence.cxx
src/medVtkInria/vtkDataManagement/vtkMetaDataSetSequence.h

Based on https://github.com/Inria-Asclepios/medInria-public/pull/247 (will be rebased after merge) [edit:rebased]
From this issue https://github.com/Inria-Asclepios/music/issues/496
This PR handles the sequence duration parameter value from the temporal fuse (datasets) method.
:m:

[mergeVolumes] add sequenceDuration management-medInria

---

src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.cpp
src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.h
src-plugins/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
src-plugins/manualRegistration/manualRegistration.cpp
src-plugins/manualRegistration/manualRegistration.h
src-plugins/manualRegistration/manualRegistrationToolBox.cpp
src-plugins/manualRegistration/manualRegistrationToolBox.h
src/medCore/gui/toolboxes/medRegistrationSelectorToolBox.cpp
src/medRegistration/itkProcessRegistration.cpp
src/medRegistration/itkProcessRegistration.h

1° From this issue https://github.com/Inria-Asclepios/medInria-public/issues/244
2° Will be rebased with https://github.com/Inria-Asclepios/medInria-public/pull/245 [edit: rebased]
3° Will be rebased with https://github.com/Inria-Asclepios/medInria-public/pull/216 [edit: rebased]
4° To be used with https://github.com/Inria-Asclepios/music/pull/493
So, this harmonized PR does:
* Manual Registration uses the undo/redo area
:m:

[manualRegistration] harmonize registration algo, use undo/redo

---

src/medCore/database/medDatabaseController.cpp
src/medCore/database/medDatabaseController.h
src/medCore/database/medDatabaseImporter.cpp
src/medCore/database/medDatabaseReader.cpp
src/medCore/database/medDatabaseRemover.cpp

I needed this for the current work I'm doing with the database, so might as well keep it.
This generalizes the use of an ```EXEC_QUERY``` macro to be used in place of ```QSqlQuery::exec()```(it was done in some places, not everywhere). I improved the macro a bit by printing out the actual query that caused the error.

Added debug message to all SQL queries

---

src/medVtkInria/vtkDataManagement/vtkMetaDataSet.cxx
src/medVtkInria/vtkDataManagement/vtkMetaDataSet.h
src/medVtkInria/vtkDataManagement/vtkMetaSurfaceMesh.cxx
src/medVtkInria/vtkDataManagement/vtkMetaSurfaceMesh.h
src/medVtkInria/vtkDataManagement/vtkMetaVolumeMesh.cxx
src/medVtkInria/vtkDataManagement/vtkMetaVolumeMesh.h

- Fix reader methods in vtkMetaSurfaceMesh and vtkMetaVolumeMesh for .mesh format, as those were incomplete:
- In volume meshes, triangles and edges are now properly read.
- In surface meshes, edges are now properly read.
- Fix signed/unsigned comparison warning in vtkMetaDataSet

[vtkDataManagement] Fix .mesh reading bug

---

src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.cpp
src-plugins/diffeomorphicDemons/diffeomorphicDemonsProcess.h
src-plugins/diffeomorphicDemons/diffeomorphicDemonsToolBox.cpp
src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/process/medAbstractProcess.h

According to this issue https://github.com/Inria-Asclepios/medInria-public/issues/341 it was not easy for the user to understand quickly if their inputs had a wrong dimension/origin or spacing.
Update: the idea is that the user just needs 2 volumes with same size and spacing (visible on the viewer). And that size and spacing errors are written separately.
:m:

[Diffeo] separate spacing, size errors. Rm origin error

---

app/medInria/medFilteringWorkspace.cpp
app/medInria/medFilteringWorkspace.h
app/medInria/medSegmentationWorkspace.cpp
app/medInria/medSegmentationWorkspace.h
src-plugins/reformat/medReformatWorkspace.cpp
src-plugins/reformat/medReformatWorkspace.h
src/medCore/gui/medSelectorWorkspace.cpp
src/medCore/gui/medSelectorWorkspace.h
src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/gui/toolboxes/medToolBox.h

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/331
Allow to easily connect and disconnect the automatic import of output from processes. It's not anymore defined by each workspace but by each process/toolbox.
By default the import is done, but you can easily stop the import in your toolboxes.
:m:

[medToolBox] standardize on process success

---

src-plugins/vtkDataMesh/readers/vtkDataMeshReader.cpp

- This PR uses the base name of the imported mesh as series description.

[vtkDataMeshReader] Fix empty series description when importing meshes

---

src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp

- When 'RemoveData(...)' method is called, the meta data set actors are now properly removed from
the actor collection.
- SmartPointer is reset to avoid potential memleaks.

[vtkDataMeshInteractor] Remove ghost actors

---

src/medCore/gui/medAbstractWorkspace.cpp
src/medCore/gui/medAbstractWorkspace.h

- Emits a signal when the layer selection changes in medAbstractWorkspace
- Add a public method to retrieve the currently selected layers.
This PR enables toolboxes to connect to this new signal and handle layer selections.
Required by https://github.com/Inria-Asclepios/music/pull/621

[medAbstractWorkspace] Layer selection changed

---

app/medInria/medDataSourceManager.cpp
src/medCore/gui/toolboxes/medToolBox.cpp
src/medCore/medPluginManager.cpp

Fixes this issue https://github.com/Inria-Asclepios/medInria-public/issues/396
It removes multiple quotation marks happening with `qDebug()<< "blabla0 " << "blabla2";`
:m:

[Log] remove multiple quotation marks

---

app/medInria/medMainWindow.cpp
src-plugins/mscExportVideo/mscExportVideo.cpp
src-plugins/mscExportVideo/mscExportVideo.h

From this issue: https://github.com/Inria-Asclepios/medInria-public/issues/404
* default names for screenshot and video export have been put.
* widgets in video export dialog file are hidden or shown according to the current export type (ogv or batch of jpeg for now).
* overwrite of jpeg batch have been developed.
:m:

[Video/Screen] def video/screen name, hide widgets, overwrite

---

app/medInria/medFileSystemDataSource.cpp
src/medCore/gui/toolboxes/medActionsToolBox.cpp
src/medCore/gui/toolboxes/medCompositeDataSetImporterSelectorToolBox.cpp

From this issue https://github.com/Inria-Asclepios/medInria-public/issues/363
* "Load" button becomes "Temporary Import" button.
* "View" button has a better explanation tooltip.
:m:

[DB] load button -> temporary import button

---

src-plugins/diffeomorphicDemons/CMakeLists.txt
src-plugins/iterativeClosestPoint/CMakeLists.txt
src-plugins/itkDataDiffusionGradientList/CMakeLists.txt
src-plugins/itkDataImage/CMakeLists.txt
src-plugins/itkDataSHImage/CMakeLists.txt
src-plugins/itkDataTensorImage/CMakeLists.txt
src-plugins/itkFilters/CMakeLists.txt
src-plugins/itkN4BiasCorrection/CMakeLists.txt
src-plugins/manualRegistration/CMakeLists.txt
src-plugins/medBinaryOperation/CMakeLists.txt
src-plugins/medClut/CMakeLists.txt
src-plugins/medMaskApplication/CMakeLists.txt
src-plugins/medSegmentation/CMakeLists.txt
src-plugins/medVtkFibersData/CMakeLists.txt
src-plugins/medVtkView/CMakeLists.txt
src-plugins/mscAlgorithmPaint/CMakeLists.txt
src-plugins/mscExportVideo/CMakeLists.txt
src-plugins/qtdcmDataSource/CMakeLists.txt
src-plugins/reformat/CMakeLists.txt
src-plugins/undoRedoRegistration/CMakeLists.txt
src-plugins/vtkDataMesh/CMakeLists.txt

From the issue https://github.com/Inria-Asclepios/medInria-public/issues/406
standardize in CMakeLists
```
${QT_LIBRARIES}
${VTK_LIBRARIES}
${ITK_LIBRARIES}
etc
```
:m:

[LIB] standardize libraries in cmakelists

---

src-plugins/itkDataDiffusionGradientList/CMakeLists.txt
src-plugins/itkDataTensorImage/CMakeLists.txt

The removal of ITKTensor from the list of libraries in two plugins caused _undefined symbols_ issues with ```itk::GradientFileReader```. ITKTensor is not provided by ITK but by TTK, so it cannot be replaced with ```ITK_LIBRARIES```.

Put back ITKTensor links

---

src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp
src/medCore/data/medMetaDataKeys.cpp
src/medCore/data/medMetaDataKeys.h
src/medCore/gui/database/medDatabaseView.cpp
src/medCore/gui/database/medDatabaseView.h
src/medCore/gui/database/mscDatabaseMetadataItemDialog.cpp
src/medCore/gui/database/mscDatabaseMetadataItemDialog.h
src/medImageIO/itkDCMTKImageIO.cpp
src/medImageIO/itkDCMTKImageIO.h

From https://github.com/Inria-Asclepios/music/issues/500 and https://github.com/Inria-Asclepios/medInria-public/issues/433
Display a QDialog with a QTreeWidget listing the metadata from the selected data in the database. Right-click on a series : Information button.
Future metadata will be automatically added in it. It would be interesting for echoes time, and other metadata from Dicom that we do not save for now. Edit: added Echo & Repetition time, and flip Angle
:m:

[Metadata] add a QDialog displaying data metadata

---

src-plugins/medVtkView/medVtkView.cpp
src-plugins/medVtkView/medVtkView.h
src/medCore/gui/viewContainers/medViewContainer.cpp
src/medCore/views/medAbstractView.cpp
src/medCore/views/medAbstractView.h

- medVtkView widget is set as the main widget of a new QMainWindow.
This allows QDockWidgets to be created around the medVtkView.

[medAbstractView] Add dockable widgets

---

src-plugins/itkFilters/itkFiltersMedianProcess.cpp
src-plugins/itkFilters/itkFiltersMedianProcess.h
src-plugins/itkFilters/itkFiltersToolBox.cpp

- neighborhood size was fixed to 1 it is now possible to choose it. Needed for sock segmentation pipeline

[itkFilters]: add choice of neighborhood size for median filter

---

app/medInria/resources/music_light.qss

fixes https://github.com/Inria-Asclepios/medInria-public/issues/491
The backgrounds of QDialog and QFileDialog are different from text area in it. 
For instance, it can be seen in the Metadata and Edit dialogs on a data, and in the "Open a file from your system" and "Open a scene from your system" QFileDialogs in a view.
:m:

[Theme] adjust text color in QDialog for light theme

---

src/medUtilities/medUtilitiesVTK.cpp

- Fix shameful bug in variance computation.
Changed:
`
Sk = Sk-1 + (xk – Mk-1)*(xk – Mk-1).
`
To
`
Sk = Sk-1 + (xk – Mk-1)*(xk – Mk).
`
where S is temporary variance, M is temporary mean, x current sample and k current iteration.

[medUtilitiesVTK] Fix variance computation

---

src/medCore/database/medAbstractDatabaseImporter.cpp

- Force the deletion of allocated readers once the pointer gets out of scope. This does not solve the underlying problem, probably related to the event loop of the import job.
- Related to #505

[Database] Hack to avoid memleak when reading files.

---

src-plugins/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp

- Fix lighting problem that caused mesh contours to be barely visible
- Increase line width from 1 to 3 pixels.
Before:
After:

[2D view] Disable lighting for meshes in 2D

---

src-plugins/medVtkView/medVtkView.cpp
src/medVtkInria/medClutEditorToolBox/medClutEditorToolBox.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/519
Delete automatically histogram if needed when the view is destroyed, create the first time histogram, then hide and show if the user clicks on the Histogram button.
:m:

[Histogram] hide/show or delete when needed

---

app/medInria/medMainWindow.cpp
app/medInria/medMainWindow.h
app/medInria/mscSearchToolboxDialog.cpp
app/medInria/mscSearchToolboxDialog.h
app/medInria/resources/music_light.qss
src/medCore/gui/commonWidgets/medQuickAccessMenu.cpp
src/medCore/gui/commonWidgets/medQuickAccessMenu.h
src/medCore/gui/settingsWidgets/medStartupSettingsWidget.cpp
src/medCore/gui/toolboxes/medSelectorToolBox.cpp
src/medCore/gui/toolboxes/medSelectorToolBox.h

For https://github.com/Inria-Asclepios/music/issues/673
Add a tool in the quickAccessMenu to choose a toolbox, then display the workspace and the toolbox. Easier for user to find a tool.
The button clicked:
The search window. The user has written "hi" and the tool is update automatically with the list of toolboxes which contain "hi" in their name/description/workspace/internal name. If the user double-click on the "Histogram Matching" line for instance here, the Filtering is opened with this toolbox.
:m:

[Search] add a search toolbox tool

---

app/medInria/medMainWindow.cpp
app/medInria/medMainWindow.h

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/486
If the user clicks on one of the exit buttons, a message dialog is display to validate the exit. If the database has temporary data, the classic `medSaveModifiedDialog` pop-up is displayed instead.
:m:

[Closing] add a pop-up to validate exit

---

app/medInria/medHomepageArea.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/141
Settings, Plugins, About, etc buttons are glued to bottom right of the application. It was the common behavior few years ago.
The 300->400 numbers is there to solve a size problem of the homepage text at its minimum size.
:m:

[Home] settings buttons at bottom right

---

src-plugins/mscExportVideo/mscExportVideo.cpp
src-plugins/mscExportVideo/mscExportVideo.h

Need https://github.com/Inria-Asclepios/medinria-superproject/pull/51
Problem seen by @paulineMig here https://github.com/Inria-Asclepios/medInria-public/pull/461 and on Jenkins for linux Ubuntu14 job - at least.
Removal of MPEG2 library which is not stable. FFMPEG works well on several OS.
:m:

[MPEG2] rm : library not stable

---

src-plugins/qtdcmDataSource/CMakeLists.txt

- Packages on macOS did not contain the libqtdcm. This explains the failure to load the qtdcmDataSource plugin when launching MUSIC.

[Packaging] Fix QtDCM tomfoolery

---

src/medUtilities/CMakeLists.txt

In MedUtilities CMakeLists.txt : Replace list of vtk & itk libraries with macro VTK_LIBRARIES ITK_LIBRARIES

[FIX] VTK_LIBRARIES ITK_LIBRARIES

---

src-plugins/mscExportVideo/mscExportVideo.cpp
src-plugins/mscExportVideo/mscExportVideo.h

Debug for 4.2.0 https://github.com/Inria-Asclepios/medInria-public/issues/534
Put back code for MPEG2, but only on Windows. On Linux and Max, compilation of FFMPEG.
Previous code was https://github.com/Inria-Asclepios/medInria-public/pull/529
This PR is linked to an other on the superproject: https://github.com/Inria-Asclepios/medinria-superproject/pull/54 
:m:

[VideoExport] avi export choose according to OS

---

app/medInria/medFilteringWorkspace.cpp
app/medInria/medFilteringWorkspace.h
app/medInria/medRegistrationWorkspace.cpp
app/medInria/medRegistrationWorkspace.h
src/medCore/gui/medAbstractWorkspace.cpp
src/medCore/gui/viewContainers/medViewContainer.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/543
Opening, closing views in every workspaces (Filtering, Registration or the others), with or without histogram is OK. And it displays the original default widget in Filtering and Registration workspaces.
:m:

[Histogram and Views] solve opening/closing views with histo or not

---

src-plugins/mscAlgorithmPaint/mscAlgorithmPaintToolBox.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/541
it cleans the toolbox at its destruction -> no more ROI from a previous step in a new Paint step in pipelines.
:m:

[Paint] solve ROI remaining between 2 pipelines steps

---

app/medInria/medFilteringWorkspace.cpp
app/medInria/medRegistrationWorkspace.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/551
At closing of the application, we do not want to put default values in half-closed views.
:m:

[Closing] handle default view widgets at closing

---

src-plugins/itkDataImage/readers/itkDCMTKDataImageReader.cpp
src/medCore/database/medAbstractDatabaseImporter.cpp
src/medCore/gui/toolboxes/medActionsToolBox.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/485 (kind of, we explain how to import Dicoms)
Fixes https://github.com/Inria-Asclepios/medInria-public/issues/545 
* Add an information widget on the File System tab in Browser, explaining how to import DICOM. Several users try selecting the files instead of the directory.
* Imported DICOM do not have empty Patient Name, Study and Series description anymore, with some empty metadata.
:m:

[DB] information about dicom import & none empty names

---

src-plugins/itkFilters/itkFiltersSubtractProcess.cpp
src-plugins/itkFilters/itkFiltersToolBox.cpp
src-plugins/itkFilters/itkFiltersToolBox.h

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/550
* The range of these spinboxes were not really set. It's better to use med[Type]Parameter.
* Subtract Filter switch to itk::ShiftScaleImageFilter because it handles pixel limits.
* Add explanation in Subtract toolbox.
:m:

[ITK Basic Filters] uses med[Type]Parameter & init range & subtract->shift ITK filter

---

src-plugins/itkFilters/itkFiltersToolBox.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/528
If there is no vertex in the Histogram Editor, the Thresholding toolbox does not update the histogram.
I just added a `if (vertices.count() > 0)`.
:m:

[itkFilters] stop update if no vertices in ClutEditor

---

cmake/FindDCMTK.cmake

Modify FindDCMTK.cmake file
Set ìphlpapi`and `ws2_32`to DCMTK_LIBRARIES Macro

[FIX] Set 2 libs to DCMTK_LIBRARIES

---

CMakeLists.txt
cmake/FixDCMTKMacInstall.cmake
src-plugins/itkDataImage/CMakeLists.txt
src-plugins/qtdcmDataSource/CMakeLists.txt
src/medImageIO/CMakeLists.txt

- Fix DCMTK link problem with itself.
- Fix QtDCM link problem with DCMTK.
Details:
- find_package(DCMTK ...) is now called once globally in medInria/CMakeLists.txt. Then, the FixDCMTKMacInstall.cmake is run to fix linking problems.
- FixDCMTKMacInstall.cmake is run a second time in plugin qtdcmDataSource, but this time it fixes QtDCM's linking with DCMTK.
N.B. This will break again when we update DCMTK version and libraries change name or suffix, e.g. libdcmdata.13.dylib instead of libdcmdata.12.dylib

[DCMTK/QtDCM] Fix macOS linking problem

---

src/medCore/data/medAbstractData.cpp

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/568
The driver's name is not nvidia, and there is no problem with mine.
It could be possible that in Ubuntu 14 (not sure), 16 and 18, the previous crash does not exist anymore. 
(By curiosity, @paulineMig can you comment this line on your code, compile, and import a data to check if the thumbnail is done? ^^)
:m:

[Ubuntu18] thumbnail - driver name

---

src/medUtilities/medUtilitiesVTK.cpp
src/medUtilities/medUtilitiesVTK.h

- Add utility method to transform arrays with point coordinates using a vtkLinearTransform
- Mainly used to refactor code

[medUtilitiesVTK] Transform point coordinates method

---

src-plugins/vtkDataMesh/readers/vtkDataMeshReader.cpp

- Fix memleak in vtkMetaDataSet when read from disk.
Any mesh that was imported from the permanent DB into the view was not cleared from memory when closing the view...

[vtkMetaDataSet] Fix memleak

---

src-plugins/itkFilters/itkFiltersToolBox.cpp
src/medUtilities/statsROI.cpp
src/medUtilities/statsROI.h

In Histogarm Analysis Toolbox.
The Wall volume computed before and after thresholding were wrong because the background value of the given masks were not 0...
Add a parameter to statsROI Process for Volume computing option.

[FIX] StatsROI : VOLUMEML

---

src-plugins/vtkDataMesh/datas/vtkDataMesh.cpp
src-plugins/vtkDataMesh/datas/vtkDataMesh.h
src-plugins/vtkDataMesh/datas/vtkDataMesh4D.cpp
src-plugins/vtkDataMesh/datas/vtkDataMesh4D.h
src/medCore/data/medAbstractData.cpp
src/medCore/data/medAbstractData.h
src/medVtkInria/vtkDataManagement/vtkMetaDataSet.cxx
src/medVtkInria/vtkDataManagement/vtkMetaDataSet.h
src/medVtkInria/vtkDataManagement/vtkMetaDataSetSequence.cxx
src/medVtkInria/vtkDataManagement/vtkMetaDataSetSequence.h
src/medVtkInria/vtkDataManagement/vtkMetaImageData.cxx
src/medVtkInria/vtkDataManagement/vtkMetaImageData.h
src/medVtkInria/vtkDataManagement/vtkMetaSurfaceMesh.cxx
src/medVtkInria/vtkDataManagement/vtkMetaSurfaceMesh.h
src/medVtkInria/vtkDataManagement/vtkMetaVolumeMesh.cxx
src/medVtkInria/vtkDataManagement/vtkMetaVolumeMesh.h

- Add a clone method and copy constructor for vtkDataMesh
- Add clone method and copy constructor for vtkMetaDataSet and children classes, i.e. vtkMetaSurfaceMesh, vtkMetaVolumeMesh, vtkMetaImageData and vtkMetaDataSetSequence.
N.B.: not implemented for vtkFiberDataSet as we are not using it for now.
- Trivializes the copy those types. As an example, some code in a process that copies the input:
**Old code**:
```cpp
// create the underlying mesh
vtkDataSet* outputMesh = nullptr;
if (inputMetaDataSet->GetType() == vtkMetaDataSet::VTK_META_SURFACE_MESH)
{
outputMesh = vtkPolyData::New();
}
else
{
outputMesh = vtkUnstructuredGrid::New();
}
outputMesh->DeepCopy(d->mesh);
// create the new abstract data
vtkMetaSurfaceMesh* outputDataSet = vtkMetaSurfaceMesh::New(); …
```

[vtkDataMesh] Copy constructor and clone method

---

src/medCore/gui/lookUpTables/medClutEditor.cpp
src/medCore/gui/lookUpTables/medLUTToXMLWriter.cpp
src/medCore/gui/lookUpTables/medLoadLUTDialog.cpp
src/medCore/gui/lookUpTables/medXMLToLUTReader.cpp
src/medCore/gui/lookUpTables/medXMLToLUTReader.h
src/medVtkInria/medClutEditorToolBox/medClutEditorToolBox.cpp
src/medVtkInria/medClutEditorToolBox/medClutEditorToolBox.h

Fixes https://github.com/Inria-Asclepios/medInria-public/issues/538
* Open a histogram, add/move vertices, changes colors
* Right click -> you can save and load vertices tables
These tables are saved/updated in a `LUTs.xml` file in the same directory as the database (can be accessed with the Log button at homepage which open this directory).
Example:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE medLUTs>
<medLUTs version="1.1">
<table title="Blue">
<node>614.6923;0.4962;0;0;255;127</node>
<node>1182.4615;0.0846;0;0;255;21</node>
</table>
</medLUTs>
```
The tool name switch from "CLUT Editor" (nobody understand) to "Histogram Editor".
:m:

[HistogramEditor] debug CLUT Editor save/load table

---

superbuild/CMakeLists.txt
superbuild/projects_modules/MUSIC_plugins.cmake

This PR adds the MUSIC plugins as an external project to medInria, to allow medInria's superbuild handle the download and configuration of the plugins. We won't have to clone the music repository separately anymore, and we won't have to manually specify the path to medInria's build, or fill in the private plugins path. This will all be done automatically, and the plugins will be placed in medInria's external projects folder (alongside dtk, ITK, VTK etc.). Ideally I would like to do this with all the repos (carmen, inria-private etc.), so that installing and configuring MUSIC will be much simpler.
Please note that:
- this will only work once the corresponding PR (to be posted) will be merged in the music repo.
- it is still possible to install the plugins as a private project, as before.

Add MUSIC plugins external project

---

src/medUtilities/medUtilities.cpp

crash when call to to switchTo3D      
mode3DParam and  renderer3DParam could not have not been initialized. (that was my case)

[minnor bug on medUtilities::switchTo3D]  unitialized variable 

---

src/layers/legacy/medCoreLegacy/data/medAbstractDataWriter.cpp
src/layers/legacy/medCoreLegacy/data/medAbstractDataWriter.h

In order to port musicPlugins writers and readers (STL/OBJ/...) theses files are necessary.

 from this PR on [medAbstractDataWriter] add files to export list of data #461 

---

superbuild/patches/dtk-1.7.1.patch
superbuild/projects_modules/dtk.cmake

Some classes inheriting from dtkAbstractData in music3 use an overriden clone method. This method calls the copy constructor of the object, which in turn calls the copy constructor of dtkAbstractData.
Something in the new dtk version causes music to crash.
This P.R. reverts the copy constructor to the previous dtk version (the one that music 2 uses)

[dtk] Fix dtkAbstractData copy constructor.

---

src/medCore/gui/viewContainers/medViewContainer.cpp

Remove patient info in globalMapping xml file when exporting scene to viewer or RHYTMIA

[FIX] - [Pipeline] - Remove patient info in globalMapping xml file

---

superbuild/patches/VTK.patch
superbuild/patches/qwt-6.3-svn.patch
superbuild/projects_modules/VTK.cmake
superbuild/projects_modules/qwt.cmake

Use the svn repo that is up to date and  can compile  with qt5.15. 
Update the patch and patch command. 
The patch include the problematic when the base class constructor is calling method on son but this one may not have finished to be constructed. 
A ticket has been create on the official repo. 
https://sourceforge.net/p/qwt/bugs/320/
The temp sol is to comment those lines and wait for qwt support answer. 
it is ok but qt5.15 is not valid with current version of medinria (vtk 8.1.2 does not compile with qt 5.15)

Adapt for qt5.15

---

superbuild/patches/dtk-1.7.1.patch

- Fixes https://github.com/Inria-Asclepios/music/issues/762
- Change the way dtk generates the writers list: previously developers had to set a priority to all of the writers, or none.
If only `n` writers had a priority set, only those `n` writers would appear in the writers list. All others would disappear.

[dtk patch] Change how dtk generates priorities

---

superbuild/projects_modules/mmg.cmake

Fix compilation error when more than one vtk is compiled on the laptop we do not need vtk in mmg

Remove use of vtk during mmg compilation

---

src/layers/legacy/medCoreLegacy/database/medStorage.cpp

The passage to MUSIC 3, and then MUSICardio, has caused the database location setting to be reset each time. This PR allows the setting that was used by the last release of MUSIC (2.4) to be retrieved if someone uses MUSICardio for the first time.
(please note it does not retrieve the setting for MUSIC 3, but this is not a problem since there are no users of MUSIC 3)
To test this you must reset your setting. On mac this is done with the following terminal command:
`defaults delete com.fr.MUSICardio database.actual_database_location`

Keep old MUSIC database location when updating to MUSICardio

---

src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReaderBase.cpp
src/plugins/legacy/vtkDataMesh/readers/vtkDataMeshReaderBase.h

- Retrocompatibility: `StudyDicomID` to `StudyInstanceUID` and  `SeriesDicomID` to `SeriesInstanceUID`

[vtkDataMesh] Add medMetaDataKeys retrocompatibility for meshes

---

superbuild/projects_modules/music-plugins.cmake
superbuild/projects_modules/openssl.cmake

compute OPENSSL_ROOT_DIR var to help other cmake proj (other plugins) to find openssl

add a variable used by other project to find openssl

---

superbuild/projects_modules/jsoncons.cmake

missing build step. 
some cmake files are not generated: jsonconsConfig.cmake, ...

missing build step in json: improve usage of the lib

---

superbuild/projects_modules/music-plugins.cmake
superbuild/projects_modules/zlib.cmake

Some minor modifications in external project cmake (music-plugins.cmake)
to be able to:
- find zlib 
- build dependencies with the good arch (x64)

WIN32 - Add ZLIB_DIR and missing CMAKE_GENERATOR_PLATFORM

---

superbuild/projects_modules/dtk.cmake
superbuild/projects_modules/eigen.cmake
superbuild/projects_modules/quazip.cmake

As https://github.com/medInria/medInria-public/pull/823
The ALWAYS_BUILD + patchs created problems at packaging step.
:m:

[Package] patchs error dtk/eigen/quazip

---

src/layers/legacy/medCoreLegacy/CMakeLists.txt
src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h
src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.cpp
src/layers/legacy/medCoreLegacy/readers/medAbstractDataReader.h

- Add medAbstractDataReader, a class that can return multiple medAbstractData instead of only one
- Adapt medAbstractDatabaseImporter to account for this new class
- Minimal cleanup of medAbstractDatabaseImporter
This P.R. is motivated by the need to read files that contain more than one "medAbstractData". This is the case with Carto and Rhythmia archives. 
Developers can now code readers that inherit from the medAbstractDataReader class instead of the dtkAbstractDataReader class.
The changes in the abstract importer where as few as possible, because I did not want to break everything.
I tested it multiple times (single data, multiple data of different types in same directory), and all seems to be working.

[Multi-part reading] Enable import of multi-part files

---

superbuild/projects_modules/music-plugins.cmake

- zlib filepath was not exposed to the project

[zlib] Fix music-plugins compilation

---

LICENSES_EXT.txt
src/app/medInria/areas/homepage/medHomepageArea.cpp
src/app/medInria/resources/medInria.qrc

From the licenses requirements, this PR adds a tab in the About box in the application with the list of licenses of our external libraries, with their sources and license URLs.
:m:

[License] add list of sources & licenses url in About

---

superbuild/projects_modules/music-plugins.cmake

An other solution for this problem https://github.com/Inria-Asclepios/music/pull/890
The parameter is sent to music-plugins even if OFF or ON.
As before, if you wan't to switch the button from ON to OFF, you need to remove music-plugins external build before, to remove the previous compiled libs.
:m:

[realtime] pass realtime parameter each time

---

src/layers/legacy/medVtkDataMeshBase/vtkMetaVolumeMesh.cxx
src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx
src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.h
src/plugins/legacy/medVtkFibersData/manager/vtkFibersManager.cxx
src/plugins/legacy/vtkDataMesh/datas/vtkDataMesh4D.cpp
src/plugins/legacy/vtkDataMesh/interactors/vtkDataMeshInteractor.cpp

- Use vtkGeometryFilter instead of vtkDataSetSurfaceFilter when adding a mesh into the view.
- Add vtkIdFilter for retrieval of original ids. This is critical for MUSICardio in mesh interactor.
- Remove code duplication
- Remove unneeded includes

[vtkImageView3D] Improvements

---

packaging/windows/WindowsPackaging.cmake
src/app/medInria/resources/medInria.rc

Based on this PR https://github.com/Inria-Asclepios/medInria-public/pull/695
The commits: https://github.com/Inria-Asclepios/medInria-public/commit/7f6bbdb6240376dad30aa06cd927cb67202b5f0e, https://github.com/Inria-Asclepios/medInria-public/commit/4276c0b52a858e0617c22742cc10b2c8002b99f4 and https://github.com/Inria-Asclepios/medInria-public/commit/bb56f6ca259c3f531813f9f189a2149c690c983f
This PR solves the icon error on Windows (medInria icon instead of MUSICardio ones, specially on task bar when pinned).
:m:

[Icons] musicardio icon in windows taskbar 

---

src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
src/plugins/legacy/voiCutter/voiCutterToolBox.cpp

Fix https://github.com/medInria/medInria-public/issues/919
This PR:
* Change the display of the output at the end of the process in `VarSegToolBox::displayOutput()`, which was crashing with a 3D/2D view
* Remove 2 non-used variable (mprOn was always set to false, and originalView not used if mprOn is set at false)
* The `d->currentView->property("Orientation")` line created a warning since there are no Orientation property here
* Handle `updateView` if the view is empty
* The explanation text is smaller because it created a small graphic bug with the information button
:m:

[VariationalSeg] solve crash avec 3D->2D view segmentation

---

src/plugins/legacy/reformat/resliceToolBox.cpp

A 1-line PR which:
* fix #920 
* fix #916
The removal of the data in the view did not reset the currentView variable.
PS: i'm going to create the same PR on medInria aswell, but we need it quickly here for the beta binaries
:m:

[Reslice] solve crashs after removing a data in view

---

src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp

Fix https://github.com/medInria/medInria-public/issues/925
This avoids the output duplication after a manual registration.
:m:

[ManualRegistration] avoid duplication in outputs

---

src/layers/legacy/medUtilities/medUtilities.cpp

During last rebase in PRs, this function has been wrongly removed. This PR adds it back.
:m:

[Rebase error] method has been discarded during last rebase

---

superbuild/projects_modules/music-plugins.cmake

Use the music-plugins repo master branch instead of music3.
:m:

[music-plugins] switch to master branch

---

src/layers/legacy/medVtkInria/vtkImageView/vtkImageView3D.cxx

Since this PR https://github.com/Inria-Asclepios/medInria-public/pull/714 some attributes of meshes were not displayed in color in 3D orientation. It was because vtkIdFilter vas not properly initialized. This PR solves this problem.
:m:

[Attributes] some mesh fields not displayed in color in 3D

---

src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.cpp
src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.h
src/plugins/legacy/polygonRoi/polygonLabel.cpp
src/plugins/legacy/polygonRoi/polygonLabel.h
src/plugins/legacy/polygonRoi/toolboxes/defaultLabelToolBox.cpp
src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h
src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.cpp
src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.h

- Add setObjectNames
- Add virtual method processOutputs (not pure) to medAbstractSelectableToolBox and polygonRoiToolbox
- Add custom metadatakey to be able to retrieve label name at the end of a pipeline step
Linked with:  [PR](https://github.com/Inria-Asclepios/music/pull/994)

Polygon roi pipeline adaptation

---

src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp
src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.h
src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp
src/layers/legacy/medCoreLegacy/database/medDatabaseRemover.cpp
src/layers/legacy/medCoreLegacy/database/medLocalDbController.cpp
src/layers/legacy/medCoreLegacy/database/medLocalDbController.h

`QSqlDatabase` connections should only be used by the thread that created them. MedInria is using the same connection everywhere, and this is causing crashes (for example when multiple data are removed at the same time).
This PR makes all database connections thread-specific by cloning the main connection for each thread that requests one (and when the thread terminates the connection will close automatically).

Make database connections thread safe

---

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp

As seen in https://github.com/Inria-Asclepios/music/pull/989 this PR allows to hide the Save button from outside, for instance from a pipeline.
(previously on https://github.com/Inria-Asclepios/medInria-public/pull/765)
:m:

[Paint] allow to forceHide the Save button

---

src/layers/legacy/medCoreLegacy/database/medAbstractDbController.h
src/layers/legacy/medCoreLegacy/database/medDataManager.cpp
src/layers/legacy/medCoreLegacy/database/medDataManager.h
src/layers/legacy/medCoreLegacy/database/medDataPacsController.h
src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.h
src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.cpp
src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentController.h
src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp
src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.h

Add an option to allow imported data to have the same name as another series in the study (no prefix added).

allow duplicate series names

---

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp
src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.h

This PR solves problems using tools in Paint:
* Paint/Erase and Magic Wand buttons do not set properly their widgets.
* Clear button was hiding buttons even if data were in the view, run twice a part of the cleaning process, then and Add and Erase buttons when shown were not handled well.
The same problems are found on medInria, this PR will need to be added there too.
:m:

[Paint] solve problems switching between tools

---

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp

In the pipelines, when resetting the paint step, the mask is not removed. This is not normal because resetting a pipeline step destroys and recreates everything (toolbox, view etc.). This was caused by annotation data being attached to the segmented data and not removed properly.

Remove annotation data when destroying paint toolbox

---

src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp

To get the crash:
* open data view with Paint toolbox opened
* do not draw something
* close the software
:m:

[Paint] crash at app closing if no painting

---

src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp

[polygonRoi] fix processsOutput crash when no roi

---

src/plugins/legacy/polygonRoi/polygonLabel.cpp

I'm testing some toolboxes, and found a bug in PolygonRoi toolbox. If the user draws a contour a little bit outside of the image border, he gets a very long spam of warnings in the terminal. This debugs solves the problem.
:m:

[PolygonRoi] avoid spam of warning if contour outside image

---

superbuild/projects_modules/medInria.cmake

Due to some merge errors i suppose there were triplicates of this `cmake_cache_args` paragraph.
:m:

[medInria.cmake] remove triplicates

---

src/layers/legacy/medCoreLegacy/database/medDataManager.cpp
src/layers/legacy/medCoreLegacy/database/medDataManager.h
src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.cpp
src/layers/legacy/medCoreLegacy/database/medDatabaseExporter.h

This PR is based on what have been done previously on MUSIC 2.4 and has been forget when we switched to ~medInria3 core. Original PR: https://github.com/Inria-Asclepios/medInria-public/pull/187 
It allows to export list of data, and it's used in MSC pipelines.
:m:

[Export] allow export of multiple data at same time

---

src/plugins/legacy/manualRegistration/manualRegistrationToolBox.cpp

The `constructContainers` method, used in pipelines for instance had a problem. Its 2 top views were not the same size.
:m:

[manualRegistration] solve top views size problem

---

src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.cpp
src/plugins/legacy/reformat/medCropToolBox.cpp
src/plugins/legacy/reformat/medCropToolBox.h
src/plugins/legacy/variationalSegmentation/varSegToolBox.cpp
src/plugins/legacy/voiCutter/voiCutterToolBox.cpp

To solve this issue: https://github.com/Inria-Asclepios/music/issues/559
To be used with https://github.com/Inria-Asclepios/music/pull/1027
Fix problems/crash of:
* medCropToolBox crash with 4D data in workspace and pipeline.
* varSegToolBox block 4D data before computing.
* voiCutterToolBox block 4D in process and handle pipeline output.
:m:

[4D data] fix Cropping, Variational Seg and VoiCutter toolboxes

---

packaging/apple/mac_packager.sh.in
superbuild/projects_modules/pyncpp.cmake

dtkDeploy handles `.dylib` files and not `.so` so we have to rename the python plugins between the two in order to be packaged properly.
In addition we compile pyncpp with rpaths which solves linking issues with the bindings (since dtkDeploy does not handle dependencies between plugins either)

python plugin packaging on macOS

---

RELEASE_NOTES.txt
packaging/apple/settings.json

This PR adds info on the release notes for 3.4, and put the proper version number in `settings.json` to be used by Jenkins for macOS.
:m:

[3.4] settings json for macOS and release notes

---

src/plugins/legacy/itkDataImage/readers/itkDCMTKDataImageReader.cpp

From this PR on medInria https://github.com/medInria/medInria-public/pull/1167
> Remove these deletions which are on static QLists. It created a crash in MUSICardio side that's why i looked at this.
:m:

[DCMTKreader] roll back on a change on static Qlist

---

src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp

Since a thumbnail setting has been added to allow or not the creation of the thumbnail at data import, there is no need to display a warning about the existence of thumbnail during the saving of a temporary data.
:m:

[Thumbnail] no need to warn if no thumbn since the thumbnail setting added

---

src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.cpp
src/layers/legacy/medCoreLegacy/gui/lookUpTables/medClutEditor.h

To avoid:
* a warning on Ubuntu because of the lack of `Q_INTERFACES(QGraphicsItem)`
* a compilation error on macOS because of its existence.
And to remove an old special comment ( 👀 ).
This PR changes the double inheritance in some histogram classes to a single one directly derived from QObjects.
:m:

[Histogram] switch QObject+QGraphicsItem to QGraphicsObject

---

src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.cpp
src/plugins/legacy/polygonRoi/viewevent/baseViewEvent.h
src/plugins/legacy/polygonRoi/viewinteractors/polygonRoi.cpp

There are some problems with Polygon ROI toolbox.
* If you want to draw a ROI with SHIFT-click, the first click was not drawing anything. This is important because some users think the toolbox is not working.
* A warning message has been solved.
* Draw a ROI, activate then deactivate repulsor: user looses the possibility to change the view contrast.
* Draw a ROI, activate repulsor, change toolbox (run `clear()` method) then click on the view -> crash.
* Activate the toolbox, draw 1 landmark, activate Repulsor, click on the view -> crash
* The last point fixed above does not crash anymore, however we loose the possibility to change the view contrast. The user needs to choose an other mouse interaction setting and go back to the original one to reset the interactor. It's annoying and it …

[PolygonROI] ROI/repulsor crashs and interactor problems

---

src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp

Same as https://github.com/medInria/medInria-public/pull/1176 but at reading.
Thumbnails could be deactivated, so no need to have warning if no thumbnail.
:m:

[Thumbnail] remove a warning reading data

---

src/plugins/legacy/itkDataImage/navigators/medVtkViewItkDataImageNavigator.cpp

From a review of the same PR on medInria, this PR removes this `for` loop which is not needed: https://github.com/medInria/medInria-public/pull/1174
:m:

[Closing] no need to delete manually labels here

---

src/plugins/legacy/medExportVideo/medExportVideo.cpp

Same PR as https://github.com/medInria/medInria-public/pull/1199
The frame rate default value was wrong during video exports, this PR changes it to a more normal one.
:m:

[Video] put a better default frame rate

---

src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp

If you open the polygonROI toolbox, add a data, draw something, then click on the button to deactivate the toolbox, the ROI is still displayed, even if you change the slice, even if you switch to another toolbox. 
This PR clears properly the toolbox/view if we deactivate it.
:m:

[PolygonRoi] clear deactivating the tlbx

---

src/layers/legacy/medCoreLegacy/gui/toolboxes/medAbstractSelectableToolBox.h

Small typo in an include in medAbstractSelectableToolBox.h
:m:

[medAbstractSelectableTlbx] typo in include

---

superbuild/CMakeLists.txt
superbuild/projects_modules/music-plugins.cmake

The music-plugins project uses the FindOpenMP module which does not always succeed on some systems. When this the case the `OpenMP_ROOT` variable must be manually set. This PR adds a check at configuration time with the appropriate message.

Check for OpenMP

---

superbuild/projects_modules/DCMTK.cmake

The previous repo for DCMTK is down since yesterday at least. This PR switches it to the Github mirror.
:m:

[DCMTK] repo not accessible anymore, switch to github

---

src/app/medInria/CMakeLists.txt
src/app/medInria/main.cpp

On Windows when Python loads an extension module that depends on other shared libraries it no longer uses `sys.paths` to load those dependencies. The function `os.add_dll_directory` must be used.

fix loading of DLLs by Python on Windows

---

src/plugins/legacy/reformat/medResliceViewer.cpp

Fix the Reslice bug from https://github.com/Inria-Asclepios/music/issues/1056
This PR adds back a (background) color to display the current selected view. 
This is needed for the user to choose the main orientation that is going to be used in the output data.
:m:

[Reslice] background color for selected view

---

src/layers/legacy/medImageIO/itkDCMTKImageIO.cpp

From PR https://github.com/medInria/medInria-public/pull/1192 and https://github.com/medInria/medInria-public/pull/1203
Fix https://github.com/medInria/medInria-public/issues/1190 "If you try to open a DICOM in which the tag origin was not properly filled the software will crash."
:m:

[itkDCMTKImageIO] when getting principal axis index assume 0 for missing origin

---

src/layers/legacy/medCoreLegacy/gui/factories/medSettingsWidgetFactory.cpp
src/layers/legacy/medCoreLegacy/gui/factories/medSettingsWidgetFactory.h

The settings order is currently undefined. This may result in general settings tabs to be placed after more obscure settings added by plugins. This PR makes some changes to the settings widget factory to place the widgets in the order that they were first registered.
(this will be relevant for my next PR since it will be adding a developer-specific tab that is getting placed in first position when I run the program)

Order settings widgets

---

src/app/medInria/medApplication.cpp
src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDevelopmentSettingsWidget.cpp
src/layers/legacy/medCoreLegacy/gui/settingsWidgets/medDevelopmentSettingsWidget.h

This PR adds a settings tab intended for developers. A while back while discussing with @Florent2305 I suggested an option that would make various functions and info visible in the application (that would be useful for developers but confusing for normal users). For the moment this will only be used in the pipelines but we can add more functions later.

add development settings

---

src/app/medInria/main.cpp

When using `callMethod` in pyncpp there is no need to convert the arguments to Python first (doing so will result in the object being converted twice, which is the equivalent of getting the boolean value of the object).

Python setup crash in call to add_dll_directory

---

packaging/windows/WindowsPackaging.cmake

When packaging on Windows, most of the dlls in the bin directory are deleted (so that only the necessary ones will be imported via fixup_bundle). The problem is the application can no longer be tested from the build directory.
This PR avoids those deletions by deleting the files from the install location instead.

(Windows) Don't delete files on packaging phase

---

packaging/windows/WindowsPackaging.cmake
src/app/medInria/main.cpp

(based on https://github.com/Inria-Asclepios/medInria-public/pull/833)
Since Python extensions on Windows are pyd files (instead of dll), we need to include those file names when installing.
Also for some reason the Python site directory is not being added to `sys.path` on startup so we have to do it manually.

(Python on Windows) add site directory and fix plugin packaging

---

src/layers/legacy/medCoreLegacy/database/medDatabaseImporter.cpp
src/layers/legacy/medCoreLegacy/database/medDatabaseNonPersistentImporter.cpp
src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp
src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.h

When importing new data medInria uses the patient name, patient birthdate and study name to identify existing patients or studies. It should be using uids instead. This causes issues with data for which these fields are empty. This PR modifies the algorithm so that the patient and study uids are used in addition to the previous tags so as to handle all cases and be retrocompatible.

Use patient Id and study uid when importing

---

src/plugins/legacy/voiCutter/voiCutterToolBox.cpp

Fix https://github.com/Inria-Asclepios/music/issues/1063
This PR:
* Solve key problem on macOS.
* Min and max intensities are kept after output is displayed on view (@fcollot in pipeline it could be useful too, setting Window/Level directly seems to bug, but setting Min and Max intensity instead is ok).
* Add a waiting toolbox when computation is done.
By the way, there is a Tab command in Voi Cutter, but it's not clear how it's working.
:m:

[VoiCutter] solve keys, min and max intensity, and add waiting toolbox

---

superbuild/CMakeLists.txt

Some options are being tested before they are defined which is causing issues. It's better to have them all defined at the beginning.

Place superbuild options earlier

---

RELEASE_NOTES.txt
src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.cpp
src/plugins/legacy/polygonRoi/toolboxes/polygonRoiToolBox.h

Fix https://github.com/Inria-Asclepios/music/issues/1074
If a data (created in a custom step of polygon roi) has not been saved in the database (temporary or not), the dataIndex is wrong. This PR fixes that problem using the data directly instead. This allows to not change the way `baseViewEvent` are handled.
:m:

[PolygonROI] fix drawing pb if data is not yet in the database

---

src/app/medInria/CMakeLists.txt
src/app/medInria/medInria.cpp
src/app/medInria/medInria.h
src/app/medInria/medInriaExport.h

This is a step towards increased integration of medInria with Python to allow the following (in future PRs):
- run medInria from Python.
- run medInria as a Python interpreter (allowing things like `medInria -m pip install numpy`).
- make medInria pip-installable.
In order to do these things we must first put the code of `main.cpp` into a separate library.
This PR moves the code of `main.cpp` into `medInria.cpp` (with associated `medInria.h`) so as to create a shared library called `medInria` (whose only exported function is `run`).
The medInria executable now contains only the following code:
```
#include "medInria.h"
int main(int argc, char* argv[])
{
return run(argc, argv);
}
```

seperate main binary into executable and library

---

src/plugins/legacy/medN4BiasCorrection/medN4BiasCorrection.cpp

COMMIT https://github.com/Inria-Asclepios/medInria-public/commit/4bbbf71d0483da39c90bfdd5bdc9976782776a3d
Based on https://github.com/Inria-Asclepios/medInria-public/pull/847
This PR removes endl at end of qDebug to avoid compilation warning.
:m:

[n4biasCorrection] remove std::endl warnings

---

RELEASE_NOTES.txt

Same release notes as in https://github.com/Inria-Asclepios/medInria-public/pull/851, to avoid future merge problem between 4.1 and master.
:m:

[4.0.3] avoid future merge problem

---

src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.cpp
src/layers/legacy/medCoreLegacy/database/medAbstractDatabaseImporter.h
src/layers/legacy/medCoreLegacy/database/medDatabasePersistentController.cpp
src/layers/legacy/medCoreLegacy/database/medDatabaseReader.cpp

Some changes are necessary in order to fix asynchronous import-related issues in the pipelines:
- Allow the direct retrieval of the data index of the newly imported data (instead of having to use signals/slots) so that the import functionality can be called manually and synchronously from the pipelines.
- Store the path of the file in the metadata, so that the file can be modified directly.

Retrieve FilePath metadata, facilitate direct call to data import

---

.github/workflows/musicardio-macos.yml

Update the Github Action script for macOS, switching to branch 4.1, updating dependencies, and standardize the sending method to fit the method i used on medInria.
:m:

[GithubAction] macos, branch 4.1, dependencies, sending method

---

src/CMakeLists.txt
src/plugins/legacy/medAlgorithmPaint/medAlgorithmPaintToolBox.cpp

I'm investigating few crashs which happen randomly at some step endings.
The processOutput method of Paint runs non needed lines which could lead to crash. It's also quicker to not do unneeded lines.
:m:

[Paint] avoid non-needed code which can crash in processOutput method

---

superbuild/external_projects_tools/EP_Initialisation.cmake
superbuild/projects_modules/tetgen.cmake

Fix https://github.com/Inria-Asclepios/medInria-public/issues/856
Conf https://github.com/Inria-Asclepios/medInria-public/pull/845
Solve "relocation R_X86_64_PC32 against symbol XXX can not be used when making a shared object; recompilé avec -fPIC" in tetgen and mmg libraries.
`ep_Initialisation_BUILD_SHARED_LIBS` was not well created and always at `ON` even if mmg and tetgen are set to compile with `BUILD_SHARED_LIBS` at `OFF`. And also `-fPIC` was not set for x86_64, only for amd64.
In addition, in `EP_Initialisation.cmake` there could be also a problem with `REQUIRED_FOR_PLUGINS` with `_DIR`.
:m:

[Unix] 4.1 compilation for tetgen and mmg
